### ISSUE TITLE
[meta] Dropping Jekyll in favor of Pandoc

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/DEPRECATED-lesson-template#1]
@gvwilson [suggested](http://software-carpentry.org/blog/2014/10/a-new-template-for-lessons.html) to use Pandoc instead of Jekyll:

> We will use Pandoc for Markdown-to-HTML conversion, so we can use {.attribute} syntax for specifying anchors and classes rather than the clunky syntax our current notes use to be compatible with Jekyll.

What the status of this?

**Comment by gvwilson** [comment]
> @gvwilson https://github.com/gvwilson suggested 
> http://software-carpentry.org/blog/2014/10/a-new-template-for-lessons.html 
> to use Pandoc instead of Jekyll:
> 
> ```
> We will use Pandoc for Markdown-to-HTML conversion, so we can use
> {.attribute} syntax for specifying anchors and classes rather than
> the clunky syntax our current notes use to be compatible with Jekyll.
> ```
> 
> What the status of this?
> 
> I am still unhappy with both options:
1. We should use the same tooling for workshop websites and for lessons, 
   so that people don't have to learn two.
2. But the Markdown processors available on GitHub don't seem to support 
   the attribute-on-opening-bar syntax for `pre` blocks that we want.

Suggestions?

**Comment by rgaiacs** [comment]
Just a prototype for pandoc: https://github.com/r-gaia-cs/lesson-template/tree/pandoc.
