### ISSUE TITLE
Improve validator for links to challenges, call outs, glossary entries, ...

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/DEPRECATED-lesson-template#104]
The pull request #103 will break the validator:

```
$ git log -1 HEAD
commit 7a59a82d833df31624b5c9c7aee24b55cd6a0f9b
Author: Raniere Silva <raniere@ime.unicamp.br>
Date:   Mon Dec 29 22:43:20 2014 -0200

    Add examples of links to part of our lessons
$ python tools/check             
ERROR:root:The provided license file should not be modified.
ERROR:root:In /home/raniere/software-carpentry/lesson-template/01-one.md: The linked page reference.html#key-word-1 exists, but the link text 'key word 1' does not match the (sub)title of that page, 'Reference'.
ERROR:root:In /home/raniere/software-carpentry/lesson-template/02-two.md: The linked page reference.html#key-word-2 exists, but the link text 'key word 2' does not match the (sub)title of that page, 'Reference'.
ERROR:root:In /home/raniere/software-carpentry/lesson-template/02-two.md: The linked page 01-one.html#challenge-title exists, but the link text 'Challenge Title' does not match the (sub)title of that page, 'Topic Title One'.
WARNING:root:Some errors were encountered during validation. See log for details.
```

**Comment by abought** [comment]
So sorry for the delayed responses during the holiday season. I'd be happy to take a look at this in the next day or two; tag me if there are other issues also needing attention.

**Comment by rgaiacs** [comment]
> So sorry for the delayed responses during the holiday season.

No problem at all. Enjoy the snow for me. =)

I'm trying to avoid send a big pull request that will be hard to review.

@abought If you could review #105 and help with it will be of great help.

**Comment by abought** [comment]
It sounds like this bug is returning back to the idea of #58 , and specifically loosening the requirement that link text much match the title of the page. I'm back from my travels and will work on this tomorrow (Saturday).

**Comment by abought** [comment]
This issue has 3 prongs, so...

Pull request has been sent for link text changes (#113). 

#105 could break some desired behavior for the validator. As alternative, I propose validating callout boxes separately; I can take that one. Here's the planned spec:
- Callout box should be a blockquoted element
- First child of callout box should have a be a header with known title text OR CSS style (pending #89 discussion)
- Callout box must have at least one child after the heading
- Some callout boxes (eg challenges) can appear more than once (validate min/max # of appearances)

**Comment by abought** [comment]
Closing this issue in favor of #134 , which covers the remaining portion of this issue.
