### ISSUE TITLE
Error running filter tools/filters/blockquote2div.py

### ISSUE THREAD

**Issue by optixlab** [swcarpentry/DEPRECATED-lesson-template#107]
After making a couple of small changes to the `01-one.md` file, I ran `make preview`. 
Prior to that, I did install pandoc as well as run `sudo pip install -r requirements.txt` (also did a pip freeze to verify that `pandocfilters` is installed). 

There is another closed issue regarding this error but it seems to have been resolved with the installation of pandoc filter. Not so in my case. Any help?

Error log:
pandoc -s -t html \
        --template=_layouts/page \
        --filter=tools/filters/blockquote2div.py \
        --filter=tools/filters/id4glossary.py \
        -Vheader="$(cat _includes/header.html)" -Vbanner="$(cat _includes/banner.html)" -Vfooter="$(cat _
includes/footer.html)" -Vjavascript="$(cat _includes/javascript.html)" \
        -o 01-one.html 01-one.md
pandoc: Error running filter tools/filters/blockquote2div.py
make: **\* [01-one.html] Error 83

**Comment by rgaiacs** [comment]
@optixlab Could you provide more information? If you could provide the changes on `01-one.md` will be very helpful (output of `git diff` is OK but if you provide the changes in a branch I or @abought could send a pull request to you as soon as we find the bug).

**Comment by abought** [comment]
Agreed, seeing the markdown would really help. (I wasn't able to find a lesson repo on your account, but that would be the best, most detailed way to debug) 

As far as I can tell, Pandoc doesn't have a verbose output mode in the current production version. Short of a better idea on where to add debugging information, I'll see about adding some checks to the validator. (`python tools/check 01-one.md`).

Also, @optixlab , does your machine have more than one python version installed? (python 2 vs 3) Might be worth confirming that pandoc is using the version of python that you installed `pandocfilters` to.

**Comment by abought** [comment]
@optixlab , do you still need help on this ticket?

**Comment by aaren** [comment]
@abought the way to debug filters is to do the piping explicitly, e.g.

```
pandoc markdown.md --to json | python filter.py | pandoc --from json --to html
```

then you get to see the full python stacktrace.

**Comment by abought** [comment]
No reply from @optixlab after 4 weeks, so closing. If the problem persists, we can reopen and address further.

**Comment by AidanDelaney** [comment]
I hit the same issue as I didn't have pandocfilters installed.

``` bash
$ pip install --user pandocfilters
```

completed my environment setup and made the build work.
