### ISSUE TITLE
Validator and build process should handle foreign language lessons

### ISSUE THREAD

**Issue by abought** [swcarpentry/DEPRECATED-lesson-template#112]
Splitting from #89 to track.

The current validator and build process only work on english-language content; CSS styles won't be added if callout box headings are in any other language. This leads to a situation where translated lessons don't build correctly unless additional markdown is added- potentially confusing.

A language flag on the validator was raised as one possible way of dealing with it. Presumably translations would be stored in a single common file accessible to both validator and pandoc filters, to keep them in sync.

**Comment by gvwilson** [comment]
Moved to https://github.com/swcarpentry/styles/issues/48
