### ISSUE TITLE
Use mathjax

### ISSUE THREAD

**Issue by aaren** [swcarpentry/DEPRECATED-lesson-template#121]
There is currently no way to use maths in the markdown lessons, beyond using raw html escapes (see https://github.com/swcarpentry/python-novice-inflammation/pull/1).

I suggest that we include a local copy of [mathjax](http://www.mathjax.org/) in the lesson template so that users can write maths using latex enclosed in `$...$`, just as you can in the IPython notebook.

Any thoughts on this?

**Comment by gvwilson** [comment]
1.  Good idea.
2.  Does Pandoc support this?
3.  Will math embedded in other files (IPython Notebooks, R Markdown) 
   survive the translation from native to plain old Markdown to HTML?

**Comment by aaren** [comment]
Pandoc doesn't really care - we can link to mathjax.js in the header.

The math is treated as a string and is transferred as-is between notebooks, markdown and html.

**Comment by ramnathv** [comment]
Mathjax has a heavy footprint. I would recommend going with a stripped down version of mathjax that gets the job done. Here is a [pruning script](https://github.com/rstudio/rstudio/blob/master/dependencies/tools/prune-mathjax) used by rstudio that slims down the version of mathjax being shipped to around 4.3 MB as compared to the full version which is around 30 MB.

**Comment by ahmadia** [comment]
If the lessons are being viewed from an Internet connection, there's no need to keep an offline copy of MathJax.  This is how the IPython Notebook works, by default.  I'd recommend doing the same.  Pandoc and MathJaX don't have great interactions when it comes to Markdown and embedded mathematics, so would also recommend exercising caution there.

**Comment by aaren** [comment]
I am in favour of using the cdn if possible, but it depends how much we value being able to render maths when offline.

A first step could be to implement this using the cdn and then think about supplying our own mathjax if that becomes a problem. IPython defaults to the cdn and allows local install on request ([see doc](http://ipython.org/ipython-doc/dev/install/install.html#mathjax))

Note the [issue](http://docs.mathjax.org/en/latest/installation.html#firefox-and-local-fonts) with firefox local files and remote fonts: firefox cannot load web fonts from a `file://` page and will fall back to image fonts.

**Comment by rgaiacs** [comment]
> There is currently no way to use maths in the markdown lessons, beyond using raw html escapes (see swcarpentry/python-novice-inflammation#1).

```
$ pandoc -f markdown -t html <<EOF
\>
EOF
<p>&gt;</p>
$ pandoc -f markdown -t html <<EOF
<
EOF
<p>&lt;</p
```

> I suggest that we include a local copy of MathJax in the lesson template so that users can write maths using LaTeX enclosed in $...$, just as you can in the IPython notebook.

I would vote for MathML.

```
$ pandoc -f markdown -t html --mathml <<EOF
\$x\$
EOF
<p><math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mi>x</mi><annotation encoding="application/x-tex">x</annotation></semantics></math></p>
```

Because (1) is the W3C recommendation and (2) we improve user experience avoiding user to download a big Javascript library that they will not use. Firefox have great support for MathML and as far as I know Safari also support it. Chrome doesn't support it but at least it is smart enough to only show the LaTeX code to the user.

I will not complain to use MathJax if we use heavy math but I only remember using it in very small cases, see https://github.com/swcarpentry/bc/issues/521.

**Comment by ahmadia** [comment]
@r-gaia-cs - MathML is almost completely unused in the scientific community, whereas LaTeX is still the underlying language used by most mathematicians and computational scientists.  I don't think we should be listening to the W3C here.

**Comment by gvwilson** [comment]
I'm with Aron on this one - the only time I've encountered MathML in the 
wild was marking up a book for a publisher eight years ago.

**Comment by wking** [comment]
On Fri, Jan 16, 2015 at 07:45:14AM -0800, Aron Ahmadia wrote:

> MathML is almost completely unused in the scientific community,
> whereas LaTeX is still the underlying language used by most
> mathematicians and computational scientists.

For my blog I have a pre-processing step that uses itex2MML to convert
a subset of LaTeX to MathML.  Then I can use LaTeX in my source, and
get MathML in my compiled HTML.

**Comment by wking** [comment]
On Fri, Jan 16, 2015 at 08:55:22AM -0800, W. Trevor King wrote:

> For my blog I have a pre-processing step that uses itex2MML…

Link: https://golem.ph.utexas.edu/~distler/blog/itex2MML.html

**Comment by rgaiacs** [comment]
@ahmadia and @gvwilson sorry if I wasn't clear. I'm +1 to use LaTeX for math. What I'm suggesting is that we only replace

```
pandoc -s -t html
```

with

```
pandoc -s -t html --mathml
```

in `Makefile` instead change `_layouts/page.html` to load MathJax.

**Will be crazy to ask anyone to write MathML by hand.** =)

**Comment by ahmadia** [comment]
Ahh, I think I am still -1.  I have yet to see MathML consistently render math aesthetically across modern browsers.  It was a good idea, but I don't think it ever received solid support from the browser community.

**Comment by cboettig** [comment]
Relevant to the MathML vs JavaScript rendering: https://code.google.com/p/chromium/issues/detail?id=152430 , apparently still some technical challenges before even major browsers like chrome can properly support mathml.  

Going with the CDN link seems pretty simple though, particularly since it seems offline use is if anything a developer issue in this context rather than a user issue?

**Comment by aaren** [comment]
:smile:
