### ISSUE TITLE
Can we remove "Other Material" section from LICENSE?

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/DEPRECATED-lesson-template#126]
The "Other Material" section contains

> Our [code of conduct](CODE_OF_CONDUCT.html) is taken from
> [this site](https://github.com/Bantik/contributor_covenant/blob/master/LICENSE),
> and is made available under the same MIT License as our software.

This make sense to our website but I believe that we can remove it from the lesson template and avoid the broken link.

**Comment by wking** [comment]
On Sun, Jan 18, 2015 at 04:40:40AM -0800, Raniere Silva wrote:

> The "Other Material" section contains
> 
> > Our [code of conduct](CODE_OF_CONDUCT.html) is taken from
> > [this site](https://github.com/Bantik/contributor_covenant/blob/master/LICENSE),
> > and is made available under the same MIT License as our software.
> 
> This make sense to our website but I believe that we can remove it
> from the lesson template and avoid the broken link.

+1.

**Comment by rgaiacs** [comment]
Done at #171.
