### ISSUE TITLE
Validator doesn't handle link to glossary item

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/DEPRECATED-lesson-template#134]
Running for https://github.com/swcarpentry/git-novice/issues:

```
ERROR:root:In /tmp/git/index.md: The linked page reference.html#version-control exists, but the link text 'version control' does not match the (sub)title of that page, 'Reference'.
```

**Comment by abought** [comment]
How do we want to handle links to glossary items?

Should it:
- Determine that the glossary page exists, or,
- Additionally check that that specific glossary term in the link text is present on the page? (eg validate the anchor within the page)

What formats will be recognized?
- Will the glossary terms always be links? (eg a previous proposal just looked for any keyword in bold)
- Should the link text be matched exactly? Or does it ignore case, spaces, hyphens, etc?

**Comment by wking** [comment]
On Wed, Jan 21, 2015 at 11:18:45AM -0800, Andy Boughton wrote:

> How do we want to handle links to glossary items?

Can't we just:
- Validate the glossary to make sure all terms define link anchors.
- Validate the pages for generic links (e.g. does the linked page
  exist, and does the linked anchor exist on that page)?

I don't understand why we need special handling for glossary links
that we don't also want for other links.

**Comment by abought** [comment]
> I don't understand why we need special handling for glossary links

Agreed in principle; I need to delve into the currently used CommonMark parser to see if it provides a way to identify named anchor links on a page. There might need to be some workarounds.

Long term we've discussed moving to pandoc's AST as a way to improve glossary handling etc. Trying to land one more feature to a stable branch before I look at rewriting the internals.

**Comment by wking** [comment]
On Wed, Jan 21, 2015 at 11:35:35AM -0800, Andy Boughton wrote:

> > I don't understand why we need special handling for glossary links
> 
> Agreed in principle…

Ah, if we're looking for a stopgap before doing this right, then I'm
fine with whatever you want ;).

> Trying to land one more feature to a stable branch before I look at
> rewriting the internals.

In my experience putting off the rewrite is often more work than just
re-architecting when you start to notice a code smell.  Do we really
need a stopgap glossary checker to land before the internal
restructuring?  I'm not familiar enough with the validator to know
what to suggest here, but I'm concerned you might be giving yourself
extra work ;).

**Comment by abought** [comment]
> Do we really need a stopgap glossary checker to land before the internal restructuring?

In this case I was referring to unrelated features, so that people had a validator that was functional for the other rules that need to be checked. Much of the AST-specific stuff is abstracted away into a separate class. 

It's not a perfect system, but my goal here is more about triage than avoiding rewrite pain. I've blocked off some time tomorrow for callouts, and @r-gaia-cs has done some spadework on the pandoc side.

**Comment by rgaiacs** [comment]
> How do we want to handle links to glossary items?
> 
> Should it:
> - Determine that the glossary page exists, or,
> - Additionally check that that specific glossary term in the link text is present on the page? (eg validate the anchor within the page)

We need to check that that specific glossary term in the link text is present on the glossary.

> What formats will be recognized?
> - Will the glossary terms always be links? (eg a previous proposal just looked for any keyword in bold)

Yes, glossary terms will always be links. After some discussion with @gvwilson we agree that links will be better.

> - Should the link text be matched exactly? Or does it ignore case, spaces, hyphens, etc?

The link text doesn't need to match to the glossary item. We will allow `[GUI](reference.md#graphical-user-interface)` for example.

> Can't we just:
> - Validate the glossary to make sure all terms define link anchors.

We already validate the glossary. (**Note**: we use a filter for add the link anchors to glossary items.)

> - Validate the pages for generic links (e.g. does the linked page exist, and does the linked anchor exist on that page)?

This is what I want to do.
