### ISSUE TITLE
Figure numbering for figure captions

### ISSUE THREAD

**Issue by zmughal** [swcarpentry/DEPRECATED-lesson-template#138]
Since Pandoc can generate figure captions for images, it would be nice to be able to use figure numbering to refer to figures from the text (Figure 1, Figure 2, etc.). Currently, the figure captions can be escaped by using the `<backslash><white-space>` syntax.

This is currently not possible directly in Pandoc, but there are some [solutions discussed](https://github.com/swcarpentry/python-novice-inflammation/pull/7#discussion_r23197234) by @r-gaia-cs that involve CSS or Pandoc filters.

(issue also filed at https://github.com/swcarpentry/python-novice-inflammation/issues/20)

**Comment by rgaiacs** [comment]
> Since Pandoc can generate figure captions for images, it would be nice to be able to use figure numbering to refer to figures from the text (Figure 1, Figure 2, etc.).

There is two problems here: (1) automatic numbering of figures and (2) link to figures from the text.

## Automatic Numbering of Figures

This one is "easy" and we have a few options:
- Use CSS, e.g. https://github.com/swcarpentry/python-novice-inflammation/pull/7#discussion_r23197234.
  
  The problem with this approach is that we will not be able to get recovery the number (at least until [this specification from WHATWG](https://books.spec.whatwg.org/#cross-references) be implemented by the web browsers that we use).
- Write your own Pandoc filter for this.
  
  Will be another piece of software that we will need to maintain.
- Send patches to Pandoc.
  
  This requires that you know Haskell. If this is the case, please read [Automatic numbering of figures and tables in HTML output](https://github.com/jgm/pandoc/issues/615) and help review [Implement figure numbering for HTML output(https://github.com/jgm/pandoc/issues/615).

## Link to Figures From the Text

Use CSS is impossible (at least for now) and write our own Pandoc filters is a **very** bad move. We will need to be involved with [this discussion](https://github.com/jgm/pandoc/issues/813).

**Comment by aaren** [comment]
@r-gaia-cs the active pandoc issue for this is https://github.com/jgm/pandoc/issues/813 and it has seen some recent activity.

As for filters, I wrote one (in python) that does automatic markdown figure numbering / linking: 

https://github.com/aaren/pandoc-reference-filter

**Comment by gvwilson** [comment]
No longer relying on Pandoc.
