### ISSUE TITLE
Need documentation for creating R lesson

### ISSUE THREAD

**Issue by jdblischak** [swcarpentry/DEPRECATED-lesson-template#149]
The current documentation does not provide instruction on how to create an R lesson. We write the lessons in R Markdown, and then convert to Markdown version that conforms to the lesson template standards by sourcing the settings in tools/chunk-options.R. Also, the Makefile already incorporates the conversion from R Markdown to Markdown.

Where would be a good location for me to add this information?

**Comment by gvwilson** [comment]
We're likely to need similar special instructions for IPython Notebooks, 
so I suggest creating a new level-2 heading in `LAYOUT.md` called 
`Writing Lessons in R Markdown` and summarizing there.
