### ISSUE TITLE
Unclear README.md

### ISSUE THREAD

**Issue by vahtras** [swcarpentry/DEPRECATED-lesson-template#15]
At the top of  README.md there nine points describing how to create a new lesson. I find the first five very unclear. There are a lot of references to "this repository", "that repository", "your repository", which make me spend a lot of time figuring out what is really meant. As there are many ways of making mistakes in git, I would prefer is these steps could be reformulated in terms of a concrete example.

**Comment by aaren** [comment]
What if we scripted steps 1-5 and put them in `bootstrap.sh` or something like that?

We can script the repo creation using the github api, with a prompt for the name of it.

**Comment by vahtras** [comment]
Yes, that would certainly help

**Comment by karinlag** [comment]
On 11/12/2014 09:50 AM, Olav Vahtras wrote:

> Yes, that would certainly help

+1 to that. That would make things even easier for newbies, and, also 
they can have a look at the script for learning purposes if they want to.

## Karin

Karin Lagesen, Ph.D.
Department of Medical Genetics
Oslo University Hospital
http://blog.karinlag.no

**Comment by gvwilson** [comment]
+1 to a script (we can use `tools/create` from the workshop-template as 
a starting point).  Would someone like to volunteer to create it?  But I 
think we should still have the manual instructions in this `README.md`, 
just as we do in workshop-template's.

**Comment by aaren** [comment]
How about a script and an instruction for running that script ('run `./bootstrap.sh`') and a link to the manual instructions, which are in a different file?

This would avoid cluttering the main README with potentially confusing instructions.

**Comment by gvwilson** [comment]
I think our two kinds of users (people who are new to Git and want the 
script, and people who are comfortable with Git and will do things by 
hand "just to be sure") will want equal billing - the README.md in the 
workshop-template repo seems to be a good compromise so far.

**Comment by aaren** [comment]
I can make a script in bash but won't be able to til the weekend. If someone else wants to have a go before then, please go ahead.

**Comment by gvwilson** [comment]
Not clear where this discussion has gotten, but does #31 address the original issue?

**Comment by rgaiacs** [comment]
I'm closing this issue as out of date due #48.
