### ISSUE TITLE
Need Makefile to not delete intermediate md files when building R lesson

### ISSUE THREAD

**Issue by jdblischak** [swcarpentry/DEPRECATED-lesson-template#156]
For building an R lesson, e.g. [r-novice-inflammation](https://github.com/swcarpentry/r-novice-inflammation), there are two steps. First the source R Markdown files are knit to Markdown. Then these Markdown files are processed via pandoc to create the html. Make automatically deletes the intermediate Markdown files.

The SWC R community has decided it would prefer to keep these intermediate Markdown files, mainly because they are convenient when inspecting files on GitHub (see the discussion [here](https://github.com/swcarpentry/r-novice-inflammation/pull/38)). Is it possible to adjust the behavior of the Makefile so that it does not delete these files?

**Comment by rgaiacs** [comment]
@jdblischak I will copy https://github.com/swcarpentry/r-novice-inflammation/pull/39.

**Comment by rgaiacs** [comment]
@abought I'm assigning this to you since you start working on #157 that covers this issue.

**Comment by abought** [comment]
#157 was closed, so there'd be no blocking issues on merging this into `lesson-template/core`. 

What is the requested change from here?
1. Pull a change from `r-novice-inflammation` into this repo, or
2. Pull the latest changes from this repo into `r-novice-inflammation`

**Comment by jdblischak** [comment]
Commit 98029a72adcebbcbd7eb1178484b92996a494621 was merged into gh-pages in PR #163, so this issue can now be closed.
