### ISSUE TITLE
where to list lesson maintainer/contact

### ISSUE THREAD

**Issue by ChristinaLK** [swcarpentry/DEPRECATED-lesson-template#158]
Hi all, quick question: should maintainers/contact people for a lesson be listed in a lesson repo, and if so, where?  We're kicking around the idea of listing maintainers in CONTRIBUTING.md...thoughts?

**Comment by gvwilson** [comment]
+1 - I think that's a great idea.

**Comment by wking** [comment]
On Wed, Feb 04, 2015 at 08:01:47PM -0800, Christina Koch wrote:

> We're kicking around the idea of listing maintainers in CONTRIBUTING.md…

Earlier discussion in swcarpentry/shell-novice#59.

**Comment by rgaiacs** [comment]
I'm closing this since our template now has `CONTRIBUTING.md`.
