### ISSUE TITLE
Proposed new labels for repo

### ISSUE THREAD

**Issue by abought** [swcarpentry/DEPRECATED-lesson-template#168]
Currently, we label issues mainly by their status (bug, defer, etc).

I'd like to propose several new labels to enable filtering by task area:
- `validator` (changes to what and how we validate)
- `build` (changes to makefile and lesson creation process)
- `documentation` (information about how to use the repository)
- `merge` or `update` (track pull requests related to resolving differences across the various forks and branches)

**Comment by wking** [comment]
On Tue, Feb 10, 2015 at 01:00:22PM -0800, Andy Boughton wrote:

> Currently, we label issues mainly by their status (bug, defer, etc).
> 
> I'd like to propose several new labels to enable filtering by task area:

I haven't been tracking the labeling debate, but +1 to orthogonal tags
for status and subject.

**Comment by gvwilson** [comment]
+1 - @r-gaia-cs can you please create the labels?

**Comment by abought** [comment]
Per swcarpentry/site/issues/813, could we also add a label for `review-requested`? 

That would help to identify pull requests/ suggestions with no owner, and provide one more way to draw attention to issues without needing to follow every email notification in detail.

**Comment by wking** [comment]
On Wed, Feb 11, 2015 at 06:36:20PM -0800, Andy Boughton wrote:

> Per swcarpentry/site/issues/813, could we also add a label for
> `review-requested`?
> 
> That would help to identify pull requests/ suggestions with no owner...

You can already filter these out using 'no:assignee' in the GitHub
issue / PR lists.

**Comment by rgaiacs** [comment]
@abought About `review-requested`, I prefer to use GitHub assignee.

**Comment by abought** [comment]
Fair point. #175 and #176 would close this ticket, then.

**Comment by willingc** [comment]
Merged #175

**Comment by rgaiacs** [comment]
New labels already set up.
