### ISSUE TITLE
Allow for a running example

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-lesson-template#192]
The Data Carpentry folks use a running example through each of their lessons; we have something like that with "Nelle's Pipeline" in our intro shell lesson (https://github.com/swcarpentry/shell-novice/), and it works pretty well.  I'd therefore like to allow-but-not-require a single level-2 heading in each topic file that _isn't_ in a blockquote, and that has the class '{.story}'.  If someone can add this to the validator and the docs, I'll add the appropriate class to the shell lesson.  No styling required on output.

**Comment by rgaiacs** [comment]
Related with https://github.com/swcarpentry/lesson-template/issues/220.
