### ISSUE TITLE
No-merge PRs for sharing unpolished lesson ideas

### ISSUE THREAD

**Issue by wking** [swcarpentry/DEPRECATED-lesson-template#193]
@daisieh floated the idea [on `discuss@`](http://lists.software-carpentry.org/pipermail/discuss_lists.software-carpentry.org/2015-March/002763.html) of having no-merge branches like swcarpentry/git-novice#62 for sharing lesson tweaks that are interesting, but maybe not interesting or polished enough to merge into a lesson's main development branch.  I think this is a good idea, and I'd been doing [something similar with workshops](http://lists.software-carpentry.org/pipermail/discuss_lists.software-carpentry.org/2015-March/002767.html) back in the swcarpentry/boot-camps days.  I'd recommend floating (but not merging) the PRs to share the idea, with interested parties converting the changes into polished pull requests for stuff that is ready for the main lesson.  Do we want to encourage this sort of behavior (I think we do)?  Where should we advertize (I think in lesson-template docs, which I'd preserve into the lessons themselves, see #124)?

**Comment by daisieh** [comment]
My logic about trying to merge the PRs into labeled (but unmerged-to-master) branches in the main repo was that in case instructors leave and decide to delete/clean their forks, we'd still have the information in the main repo. I don't know if it would be a lot of trouble for perhaps the repo maintainers to do that? Like, the instructor (if they have changes they want to share, and we encourage them to do so), makes a PR against gh-pages, but if we see that there are significant diffs that we'd like to keep a record of (as opposed to just cosmetic changes or deletes), we could make a named archive branch and merge the PR there.

**Comment by gvwilson** [comment]
My concern is that these will pile up and never be read (much less merged).

**Comment by wking** [comment]
On Mon, Mar 09, 2015 at 11:19:04PM -0400, Ivan Gonzalez (@iglpdc) wrote [1](http://lists.software-carpentry.org/pipermail/discuss_lists.software-carpentry.org/2015-March/002777.html):

> So the workflow would be:
> 
> 1) make your whole modified lesson a new branch named after your
>    workshop,
> 2) make a PR labeled "workshop-archive" also named after your
>    workshop and close it (maybe after a few days after),
> 3) people pick from your branch what is useful and maybe merge into
>    master,

This sounds good, yeah.

> 4) the branch never gets deleted and serves as archive

I don't think this matters (and @daisieh raised a similar concern
[2](https://github.com/swcarpentry/lesson-template/issues/193#issuecomment-77990661)).  I don't want to delete my fork of lessons-template for the
test, but I just created a branch, PRed that branch, and deleted the
source branch in #194.  The pull request is still there with the PRed
branch, and there's a little note saying I deleted the source branch.
So instructors can freely delete the source branch (and likely their
whole lesson fork), and we'll still have their submitted commits
available for inspection and merging.

**Comment by wking** [comment]
On Tue, Mar 10, 2015 at 05:44:02AM -0700, Greg Wilson wrote:

> My concern is that these will pile up and never be read (much less
> merged).

Ignoring close PRs shouldn't be too hard ;), so I don't see any
downside.  And I see an upside in increased discoverability in the
event that someone does want to look through the submission (or
searches for something they're interested in, e.g. with [1](https://github.com/swcarpentry/git-novice/issues?q=detached+head), to see if
anyone's done that before).  So:
- What's the downside to a bunch of unmerged workshop-archive PRs?
- How useful is the discoverability upside?
- Is there a better way to increase discoverability?

My current feelings are, “there isn't one”, “moderately useful to
maintainers and folks looking for a particular non-standard topic”,
and “not that I can think of”.

**Comment by wking** [comment]
On Tue, Mar 10, 2015 at 10:00:31AM -0700, W. Trevor King wrote:

> - How useful is the discoverability upside?
>   …
>   My current feelings are… “moderately useful to maintainers and folks
>   looking for a particular non-standard topic”…

To back this up with a real-world example, Ethan just referenced work
from swcarpentry/git-novice#62 as seed content for additional Git
motivation [1](https://github.com/swcarpentry/git-novice/pull/49#issuecomment-78088258).

**Comment by iglpdc** [comment]
I see. We could try.

I see a minor downside if people uses this instead of PRs against master. For example, someone has a lot of useful stuff in her branch, but I find it hard for people to go through all her changes to create new PRs form there (as a general rule). So I think most of the times who's archiving the branch would be the one creating PRs from her archived material. The minor issue I see is people expecting others to do it (their changes are already archived) and at the end having nothing done. 

I agree that would be useful for non-standard topics/workshops if the archived PR describes well the differences with the standard.

**Comment by jiffyclub** [comment]
This could in a way encourage people to merge things back to the main lesson. That is, they open their archive PR and people reviewing it can call out certain things they'd like to see merged back into the main lesson. Then, hopefully, the person who opened the archive PR would make new PRs with the requested updates.

**Comment by wking** [comment]
On Tue, Mar 10, 2015 at 10:56:30AM -0700, Ivan Gonzalez wrote:

> I see a minor downside if people uses this instead of PRs against master.

Absolutely.  I prefer PRs against the main lesson branch where:
1. The change is an evolutionary improvement on the main lesson.
2. The submitting author is capable of generating such PRs (see #159
   where @jdblischak and @gvwilson express concern about the
   feature-branch approach being overly complicated).
3. The change isn't part of a maintained alternative lesson
   (swcarpentry/site#870).

I think the no-merge, archival PR works best for floating
revolutionary changes (before getting into the fuss of refactoring the
changes into feature branches) and for submitting changes for authors
who are not able to develop or reconstruct feature branches on their
own.

> I agree that would be useful for non-standard topics/workshops if
> the archived PR describes well the differences with the standard.

Any wording suggesting this workflow should explain very clearly the
benefits of a good cover-letter on the PR which describes the changes.

**Comment by daisieh** [comment]
I don't think this is supposed to _replace_ PRs against master: I think that instructors would find it less intimidating to share their mods this way, and then in the comments, people could encourage the instructor to make a PR to push the best changes to master.

**Comment by daisieh** [comment]
I don't think this is supposed to *replace* PRs against master: I think that instructors would find it less intimidating to share their mods this way, and then in the comments, people could encourage the instructor to make a PR to push the best changes to master.

**Comment by daisieh** [comment]
I don't think this is supposed to *replace* PRs against master: I think that instructors would find it less intimidating to share their mods this way, and then in the comments, people could encourage the instructor to make a PR to push the best changes to master.

**Comment by daisieh** [comment]
From my conversations with the other instructors at our workshop, I found that people do find it intimidating to spontaneously suggest changes to master; people feel like the material at master is that way for a reason, and their changes are just their own thing, not something that others want. I'd like to get around that by making people feel like their changes are not being forced on others, just presented to share.

**Comment by wking** [comment]
On Wed, Mar 11, 2015 at 02:39:37PM -0700, Daisie Huang wrote:

> From my conversations with the other instructors at our workshop, I
> found that people do find it intimidating to spontaneously suggest
> changes to master; people feel like the material at master is that
> way for a reason, and their changes are just their own thing, not
> something that others want. I'd like to get around that by making
> people feel like their changes are not being forced on others, just
> presented to share.

I'm happy to do whatever it takes to make PRs against the main
development branch (core or gh-pages here, and gh-pages for downstream
lessons).  PRs are just “here are some possible changes, and my
motivation for them is …”, so I'd encourage folks who notice such
intimidation to encourage the potential submitter to just open the PR
;).  If it gains traction and gets merged, great :).  If not, the
reasons the maintainers put forward for not merging it can help guide
future contributors.  But just because _I_ don't feel the need to have
rock-solid motivation for each PR doesn't mean we won't benefit by
putting the barrier for contribution as low as we can.  I think
no-merge PRs are useful for folks who don't have the time or
Git-comfort for constructing feature-branch PRs.  If they also appeal
to a segment of the population that's not comfortable submitting
feature-branch PRs, and let us start the conversation towards getting
those people comfortable enough to submit feature-branch PRs, that
would be awesome :).

**Comment by wking** [comment]
The last few comments here are all in favor of the change.  To move
this towards a consensus resolution, I want to make sure folks who
have voiced concerns feel that their concerns have been addressed.
Issues that have been raised:
- No-merge PRs pile up [1](https://github.com/swcarpentry/lesson-template/issues/193#issuecomment-78045673).  I tried to address this in [2](https://github.com/swcarpentry/lesson-template/issues/193#issuecomment-78098384)
- It could be hard to find useful changes in no-merge PRs [3](https://github.com/swcarpentry/lesson-template/issues/193#issuecomment-78110199).  I
  tried to address this in [4](https://github.com/swcarpentry/lesson-template/issues/193#issuecomment-78153249), with a reminder about good cover
  letters.
- We don't want folks to get lazy and submit a no-merge PR instead of
  more targetted feature-branches [3](https://github.com/swcarpentry/lesson-template/issues/193#issuecomment-78110199).  All the comments after [3](https://github.com/swcarpentry/lesson-template/issues/193#issuecomment-78110199)
  talk about encouraging the no-merge submitter to create their own
  feature branches, with the option that others step in and talk them
  through the process (or pick up a feature they like themselves).

Does anyone feel like these concerns are still blockers?  Are there
any other concerns we want to consider?  Otherwise I think it's time
to discuss where we want to put this suggestion so we can start work
on a PR outlining the workflow.

**Comment by iglpdc** [comment]
I'm good. I think you summarized it pretty well. I like the idea of evolutionary vs revolutionary changes.

**Comment by daisieh** [comment]
Yay! I'm glad my idea is getting traction :)

**Comment by gvwilson** [comment]
Wrapping discussion.
