### ISSUE TITLE
Challenges at discussion

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/DEPRECATED-lesson-template#208]
From https://github.com/swcarpentry/git-novice/pull/80,

```
ERROR:root:In /home/raniere/software-carpentry/lesson-template/discussion.md: Found callout box with unrecognized style 'challenge'
```

Need to change `tools/check.py` to allow challenge call out at `discussion.md`.

**Comment by iglpdc** [comment]
See also the discussion in #199. Shouldn't we first agree on the format of `discussion.md` before changing the script?
