### ISSUE TITLE
Allow code within blockquote2div

### ISSUE THREAD

**Issue by fmichonneau** [swcarpentry/DEPRECATED-lesson-template#211]
I think this mostly affects the R lessons but it probably wouldn't hurt for the other lessons as well.

Currently, there are challenges that includes chunks for R code such as this:

``````
> ## Challenge -- Using loops {.challenge}
> 1. R has a built-in function called `seq` that creates a list of numbers:
>
```{r}
seq(3)
```
> using seq....
``````

after being processed with knitr it gets converted to something like this

```
> ## Challenge -- Using loops {.challenge}
> 1. R has a built-in function called `seq` that creates a list of numbers:
>


~~~{.r}
seq(3)
~~~

 ~~~{.output}
 [1] 1 2 3
 ~~~


 > using seq....
```

basically it introduces empty lines around the processed chunks. These empty lines mislead the blockquote2div scripts and put the limits to the div too early.

![untitled](https://cloud.githubusercontent.com/assets/5502922/6813885/c302c9d6-d24f-11e4-9421-08b43e319c43.png)

The solution would be add a `>` on the inserted empty lines so it would like this:

```
> ## Challenge -- Using loops {.challenge}
> 1. R has a built-in function called `seq` that creates a list of numbers:
>
>
>
~~~{.r}
seq(3)
~~~
>
 ~~~{.output}
 [1] 1 2 3
 ~~~
>
>
> using seq....
```

Could someone implement this in blockquote2div?

**Comment by rgaiacs** [comment]
```
$ pandoc <<EOF
> Foo
~~~
bar  
~~~  
> continue
EOF
<blockquote>
<p>Foo <sub><sub><sub> bar </sub></sub></sub> continue</p>
</blockquote>
```

is different from

```
$ pandoc <<EOF
> Foo
>  
> ~~~
> bar
> ~~~     
>  
> continue
EOF
<blockquote>
<p>Foo</p>
<pre><code>bar</code></pre>
<p>continue</p>
</blockquote>
```

Can we change knitr?

**Comment by rgaiacs** [comment]
I requested this feature to knitr, see https://github.com/yihui/knitr/issues/1022.

**Comment by fmichonneau** [comment]
Hi @r-gaia-cs 

Thanks for submitting the feature request with knitr. That would make things simpler if it was directly supported. I realize as your example demonstrates that the two chunks of code have different output. However, if our blockquote2div could add the extra `>` where needed in the blank lines it would fix the location of the box and it's what matters the most at this stage.

The Rmd file for `03-loops` gets rendered like this:

```
> ## Challenge - Using loops {.challenge}
>
> 1. R has a built-in function called `seq` that creates a list of numbers:


~~~{.r}
seq(3)
~~~


~~~{.output}
[1] 1 2 3

~~~
```

![screenshot1](https://cloud.githubusercontent.com/assets/5502922/7219935/5d2e451a-e684-11e4-8069-1b59cacd9a45.png)

If we add the `>` (here done manually in the markdown file).

```
> ## Challenge - Using loops {.challenge}
>
> 1. R has a built-in function called `seq` that creates a list of numbers:
>
>
~~~{.r}
seq(3)
~~~
>
>
>
~~~{.output}
[1] 1 2 3
~~~
>
> Using `seq`, write a function that prints the first **N** natural numbers, one per line:
>
>
>
>
~~~{.r}
print_N(3)
~~~
>
>
>
~~~{.output}
[1] 1
[1] 2
[1] 3
~~~
>
```

Then we get what we want:

![screenshot2](https://cloud.githubusercontent.com/assets/5502922/7219960/0b692a78-e685-11e4-96b6-7033c57dc1e9.png)

**Comment by rgaiacs** [comment]
@fmichonneau `blockquote2div` doesn't process the raw Markdown file. It process Pandoc's internal AST using Pandoc's navigation function.

```
$ pandoc -t json -o out <<EOF
> Foo

~~~
bar
~~~

> continue
EOF
$ json_reformat < out
[
    {
        "unMeta": {

        }
    },
    [
        {
            "t": "BlockQuote",
            "c": [
                {
                    "t": "Para",
                    "c": [
                        {
                            "t": "Str",
                            "c": "Foo"
                        }
                    ]
                }
            ]
        },
        {
            "t": "CodeBlock",
            "c": [
                [
                    "",
                    [

                    ],
                    [

                    ]
                ],
                "bar"
            ]
        },
        {
            "t": "BlockQuote",
            "c": [
                {
                    "t": "Para",
                    "c": [
                        {
                            "t": "Str",
                            "c": "continue"
                        }
                    ]
                }
            ]
        }
    ]
]
```

Will be extremely hard to change `blockquote2div` to do what you want. A more suitable approach is use [json from Python Standard Library](http://docs.python.org/3.5/library/json) to make the changes but we will need to be very careful to know corrupt the AST and that's why I want to avoid this.

IMHO will be easy to change knitr but I need to understand how it work under the hood.

**Comment by rgaiacs** [comment]
@fmichonneau I'm closing this since this was fixed on knitr.
