### ISSUE TITLE
Prep for 5.3 Lessons Release

### ISSUE THREAD

**Issue by jiffyclub** [swcarpentry/DEPRECATED-lesson-template#224]
This post is targeted at the @swcarpentry/lessons subcommittee, but everyone is invited to contribute.

In the next month or two we're planning to declare our lessons to be at version 5.3 and try to make permanent archives of each lesson with citable [DOIs](http://en.wikipedia.org/wiki/Digital_object_identifier). In the lead up to that we've got some work for which we're looking for volunteers:
# What to Archive

We need to make sure that our lesson releases have everything they need and not too much they don't. So what does that actually mean? Do we need to compile anything, what can we delete?
# How To Actually Make the DOI and Archive

The actual mechanics of this process. [This GitHub guide](https://guides.github.com/activities/citable-code/) is probably a good starting point, but we need someone to give it a try to see whether it makes sense for us, and maybe compare it to other options like [Code as a Research Object](http://mozillascience.github.io/code-research-object/).

Would anyone from the @swcarpentry/lessons team or the broader SWC community like to volunteer for one of those tasks? If so, please leave a comment!

**Comment by rgaiacs** [comment]
I can also help someone to use GitHub API.

**Comment by wking** [comment]
On Thu, Apr 16, 2015 at 02:54:27PM -0700, Matt Davis wrote:

> We'd like to create a "Version 5.3" milestone on every lesson repo
> so maintainers can assign the milestone to the PRs and issues that
> they want resolved before the release. To avoid a bunch of manual
> work we'd appreciate someone making a Python script to create the
> milestone on each lesson repo via the GitHub API. I'm a fan of the
> github3py API wrapper, and I think using that we can make a little
> script to help us out. Since I have some experience with github3py,
> so I'm happy to help someone write this script if they are curious
> to learn about the GitHub API.

The GitHub API is simple enough that we probably don't need a wrapper.
I put together a milestone-and-issue checklist pusher for Greg last
weekend [1,2] which pushed arbitrary templates (like [3](https://github.com/wking/swc-lead-instructor-checklist)).  We can use
that out of the box with something like:

  $ pip install --user github-push-issues
  $ mkdir version-5.3
  $ cat <<EOF >version-5.3/README.md
  # Version 5.3

  Get ready for a new release!
  See https://github.com/swcarpentry/lesson-template/issues/224
  EOF
  $ github-push-issues.py -u wking -r wking/test-workshop version-5.3

which creates the v5.3 milestone listed here [4](https://github.com/wking/test-workshop/milestones).  To make life easier
for lesson maintainers, we'd probably want to push that simple
template to a GitHub repository (like I did with [3](https://github.com/wking/swc-lead-instructor-checklist)), and then use:

  $ pip install --user github-push-issues
  $ github-push-issues.py -u wking -r wking/test-workshop \

>   https://github.com/wherever-we-put/the-template/archive/master.zip

**Comment by daisieh** [comment]
Ha, I already accidentally did it manually for the git-novice repo.

**Comment by wking** [comment]
On Thu, Apr 16, 2015 at 05:23:21PM -0700, Daisie Huang wrote:

> Ha, I already accidentally did it manually for the git-novice repo.

That's fine too ;).  Creating a single milestone isn't a terrible,
multistep task.  So whatever is easiest for each lesson maintainer…

**Comment by jiffyclub** [comment]
Yeah creating the milestone is definitely something we could ask the maintainers to take care of.

**Comment by rgaiacs** [comment]
I remembered that I wrote a shell script to setup the labels,
see https://github.com/swcarpentry/lesson-template/blob/gh-pages/tools/setup-labels,
that shouldn't be hard to change for setup the milestone.

@jiffyclub Do you have someone that could do the changes in my script?

**Comment by wking** [comment]
On Sat, Apr 18, 2015 at 06:01:24AM -0700, Raniere Silva wrote:

> I remembered that I wrote a shell script to setup the labels,
> see https://github.com/swcarpentry/lesson-template/blob/gh-pages/tools/setup-labels,
> that shouldn't be hard to change for setup the milestone.

While we're talking about scripting lesson/milestone creation, I just
took ghi [1](https://github.com/stephencelis/ghi/) for a spin, and after patching my gem-installed version
to fix [2](https://github.com/stephencelis/ghi/pull/166) it seems pretty convenient for these sorts of one-off
tasks.
