### ISSUE TITLE
Documentation for how to create and preview HTML has gone missing

### ISSUE THREAD

**Issue by hlapp** [swcarpentry/DEPRECATED-lesson-template#227]
I seem to remember that this used to be in the top-level `README.md`, but now there is no such file anymore, nor another one that documents it. There is PR #215, which if I understand correctly would move this to a subdirectory (which still doesn't obviate the need for a top-level README to point people where to look), but that PR remains in a holding pattern.

The problem is that there is no other place to go. The `CONTRIBUTING.md` refers back to this repo and thus makes a (currently) false assertion:

> This lesson is based on the template found at https://github.com/swcarpentry/lesson-template. That repository has instructions on formatting and previewing lessons.

Worse yet, actual lessons do the same, for example the [git-novice lesson](https://github.com/swcarpentry/git-novice/blob/gh-pages/README.md):

> Please see https://github.com/swcarpentry/lesson-template for instructions on formatting, building, and submitting lessons, or run make in this directory for a list of helpful commands.

Perhaps every current contributor to SWC has the how-to-preview internalized, but for everyone else this is quite bad.

**Comment by rgaiacs** [comment]
@hlapp Thanks for the report.

We move that information to https://github.com/swcarpentry/lesson-example/.

> Perhaps every current contributor to SWC has the how-to-preview internalized, but for everyone else this is quite bad.

We will try to fix the information as soon as possible.

**Comment by gvwilson** [comment]
Added notes to all the repos with pointers to lesson-example.
