### ISSUE TITLE
Provide a template for localization

### ISSUE THREAD

**Issue by tbekolay** [swcarpentry/DEPRECATED-lesson-template#229]
@statkclee is currently translating [`python-novice-turtles`](https://github.com/swcarpentry/python-novice-turtles/pull/7) into Korean, which is fantastic! I'm not sure if this is the first instance of a lesson being localized (I noticed #112 but nothing else), but in any case, I feel that this repository should include some instructions as to how we want localized versions of lessons to be done. If these instructions exist already (in a blog post or some such) please point me to them and I'll pull them into this repository!

**Comment by rgaiacs** [comment]
As far as I can remember, I, @gvwilson and @wking (I believe that I'm missing someone, sorry in advance for that) mostly agree to follow the [workflow of ProGit2](https://github.com/progit/progit2/blob/master/CONTRIBUTING.md#translations) but we didn't have time to write the minor details. I believe that the best approach should be:

## Web way
1. Use https://import.github.com/ to create a copy of the lesson you want to translate. E.g. https://github.com/r-gaia-cs/python-novice-turtles-pt for the portuguese translation of https://github.com/swcarpentry/python-novice-turtles/.
2. Start translating 
   - `CONDUCT.md`
   - `CONTRIBUTING.md`
   - `DESIGN.md`
   - `FAQ.md`
   - `index.md`
   - `LAYOUT.md`
   - `LICENSE.md`
   - `README.md`
   
   **Changes at `tools/` could be needed.**
3. Let Software Carpentry community know about your plan. We will add it at http://software-carpentry.org/lessons.html as **work in progress**.
4. Translate the lesson.
5. Let Software Carpentry know that the translation is complete. We will add it at http://software-carpentry.org/lessons.html as **stable**.

## Command line way
1. Create a new repository at GitHub, e.g. https://github.com/r-gaia-cs/python-novice-turtles-pt for the portuguese translation of https://github.com/swcarpentry/python-novice-turtles/, and push the commits from the english lesson.

The others steps are the same.

@statkclee This works for you?

@jiffyclub What do you think about it?

**Comment by statkclee** [comment]
@r-gaia-cs @tbekolay @jiffyclub I didn't have sufficient time to study this issue except the Korean translation. However, I think that it's very common around software products/services and we can find best practices on this issue, localization. Is there anyone who can share experiences, architectures, stories, and so on?

**Comment by gvwilson** [comment]
Moved to https://github.com/swcarpentry/styles/issues/48
