### ISSUE TITLE
Summarize tools/check.py output

### ISSUE THREAD

**Issue by tbekolay** [swcarpentry/DEPRECATED-lesson-template#230]
I'm not familiar with the `tools/check.py` code, so I don't know how feasible this is, but I think it would be very helpful to provide a summary at the end, primarily listing how many errors were encountered when checking the files. When dealing with a lesson repository, it's not easy to see whether a PR has introduced new errors or fixed old errors if there are already 20+ errors; it's simply too hard to visually compare the before and after output. However, if the check function listed something like "23 errors found in 12 files" it would be easy to see how a PR has impacted the quality of the lesson (as measured by check.py errors).

**Comment by rgaiacs** [comment]
> so I don't know how feasible this is, but I think it would be very helpful to provide a summary at the end,

@tbekolay Thanks for the feedback. This is feasible and should be easy (using a global variable). We probably need to do some code refactoring to avoid code duplication on this.

**Comment by abought** [comment]
That's a good idea. I'm slowly getting caught up after the move; I'd love to clear a few hours this week/weekend to do some more work on `check.py`. Are we still on track for a mid-month version release?

As a very rough approximation until error counting is built in, it's always worth mentioning the power of combining unix utilities. (though this is not the long term way- just something useful for now)

Eg,

Number of errors:
`python tools/check.py | grep "ERROR" | wc -l`

Number of files:
`python tools/check.py -d | grep "Beginning validation" | wc -l`
