### ISSUE TITLE
Add a "Getting ready" callout to index.md

### ISSUE THREAD

**Issue by iglpdc** [swcarpentry/DEPRECATED-lesson-template#233]
A current problem of our lessons is that some need a particular set of data files. For example, shell-novice needs Nelle's filesystem files and python-inflammation-novice the inflammation data. The solo learner has no clue on how to get these files and in workshops we have to find a way to make them available. See [this thread in our mailing list](http://lists.software-carpentry.org/pipermail/discuss_lists.software-carpentry.org/2015-May/002974.html).

I propose to make a dedicated callout box at the lesson-template level, called "Getting ready", similar to "Prerequisites", with  the instructions and links on how to get the files (which are stored in the repo already).

Solo learners would follow this instructions to get them on their own, and instructors in workshops can link (using the `#getting-ready` anchor) to these instructions. In fact, we could provide (or explain it in the instructor checklist) a link in the workshop template (as is the same for all lessons), so, by default, clicking on the lesson name on the workshop's schedule takes you there.

**Comment by gvwilson** [comment]
Hm - in the lesson template, or in the workshop template?

**Comment by iglpdc** [comment]
The callout box goes in the lesson template, but I see that the layout of this repo has changed. I think the "Getting ready" box should be treated the same as the "Prerequisites" box, so an `index.md` for a lesson should be:

```
---
layout:lesson
title: lesson title
---
Paragraph of intro material

> Prerequisites {.prereq}
> 
> What learners need to know before the lesson

> Getting ready {.ready}
> 
> What learners need to do before the lesson

## Topics
(...)
```

The `tools/check.py` script should warn if the callout box is missing.

Then, in the **workshop-template** repo, we could use these links in the schedule section, either by default or explaining how to do it in the instructors' checklist.

Then we have to add the callout boxes in each lesson and add a zip file to each lesson repo with the corresponding data.

It is a "system-wide" PR, but worthy I think. :-) I could do it during the weekend.

**Comment by rgaiacs** [comment]
@iglpdc We are working at the same time. Please check https://github.com/swcarpentry/lesson-example/pull/3.

@gvwilson Does we have time to include this on v5.3?

**Comment by iglpdc** [comment]
Yep, I did already. I wasn't aware of the new `lesson-example`repo.

**Comment by abought** [comment]
Just to confirm: this is an optional callout, correct? The definition as written will allow either 0 or 1 to be present.

**Comment by rgaiacs** [comment]
> Just to confirm: this is an optional callout, correct?
> The definition as written will allow either 0 or 1 to be present.

This will be a requirement box.
You can say, **you are ready to go**.

I will make the changes today.
