### ISSUE TITLE
tools/check.py doesn't work with the glossary entries 

### ISSUE THREAD

**Issue by iglpdc** [swcarpentry/DEPRECATED-lesson-template#237]
I was trying to fix an error reported by `tools/check.py` in `git-novice`. The error is:

```
...
ERROR: In /Users/ivan/Documents/swc/git-novice/reference.md: At glossary entry 'change set' Subsequent lines of definition must start with '     '.
ERROR: In /Users/ivan/Documents/swc/git-novice/reference.md: At glossary entry 'change set' Subsequent lines of definition must start with '     '.
...
```

Meaning that the lines after the first in the `change set` glossary entry _don't_ start with four spaces. But they do.

By digging into the script, I found:
- only the first glossary entry is checked, because there's a conditional that is short-circuited,
- the first glossary entry always fails the test, because the parser for Markdown strips the whitespace at the beginning of the line, defeating the check for whitespace at the beginning of the line.

This is the minimal example that shows the bug:

```
import CommonMark

markdown = '    here    '
parser = CommonMark.DocParser()
ast = parser.parse(markdown)
print ast.children[0].strings
```

outputs:

```
['here    ']
```

I guess the same error is showing up in all the lessons. 

I don't know how to fix it, because I don't know how the parser works.

**Comment by rgaiacs** [comment]
@iglpdc I already fixed this a few days ago: https://github.com/swcarpentry/lesson-template/commit/45dbfcdc855b3c299acab1ee80bbf949c69ce395.

Sorry to not warning anyone about this. I will merge the changes that we talk yesterday soon.

**Comment by iglpdc** [comment]
Great! Busy days, eh? :-)
