### ISSUE TITLE
Include CSS as submodule

### ISSUE THREAD

**Issue by kynan** [swcarpentry/DEPRECATED-lesson-template#241]
Apologies if this has already been discussed: what are the reasons for merging changes from swcarpentry/css into this (and other) repositories rather than including css as a submodule?

One reason could be simplicity for the "user" who doesn't need to deal with submodules.

For developers I would personally find submodules easier to work with and the separation would feel "cleaner".

**Comment by gvwilson** [comment]
For simplicity - our experiences with submodules in the past have been 
unpleasant.
