### ISSUE TITLE
What changes should we make for our 5.4 release?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-lesson-template#242]
What changes should we make to the template for the next release?

**Comment by gvwilson** [comment]
Remove the `Legend` section - nobody's sure what to do with it anyway.

**Comment by gvwilson** [comment]
Allow sub-headings, but warn when there are more than 3-4 in a topic file.

**Comment by gvwilson** [comment]
Require a section at the start of each topic giving an example of what the learner will be able to do after the topic has been covered (which will also help people decide whether they can skip it).

**Comment by rgaiacs** [comment]
@gvwilson Can we create one issue for each change and make it with "Discussion" and "5.4"?

**Comment by gvwilson** [comment]
I strongly prefer to keep all the discussion here until we know what 
we're doing - it means there's just one place for people to look.

**Comment by jevbelikov** [comment]
Could add a differently styled call-out for warning/common source of mistakes (thinking of O'Reilly books' trap symbol).

**Comment by rgaiacs** [comment]
Improve the navigation between topics, i.e. have "next" and "previous" links.

**Comment by rgaiacs** [comment]
Option for download the lesson as EPUB (for off-line reading).

**Comment by rgaiacs** [comment]
Option for download the lesson as PDF (for printing). **Good formatting for printing isn't easy to accomplished but we could at least provide a reasonable PDF for instructors/learners that want to print the lessons.**

**Comment by chendaniely** [comment]
There are usually options to print to PDF these days, and from the print preview, the lessons don't look too bad.  What special formatting would be needed for pdfs?

**Comment by rgaiacs** [comment]
Translation guidelines and support. See https://github.com/swcarpentry/python-novice-turtles/pull/7.

**Comment by rgaiacs** [comment]
> There are usually options to print to PDF these days, and from the print preview, the lessons don't look too bad. What special formatting would be needed for pdfs?

@chendaniely Firefox, Chrome and, **I think**, Safari support create PDF from HTML pages. We just need a few improvements in our CSS for make this better. What happens is that we are breaking the lessons in small topics (e.g. the Git lesson doubled the number of HTML files for 5.3) and this makes hard for learners and instructors print all the lesson(s). Having a PDF will make printing very easy for everyone that want to do it and for us isn't very hard to do that as long as we don't be picky about the output. [I have a draft for that](https://github.com/r-gaia-cs/swc-lesson-template/tree/core-epub-and-pdf) that I just need to clear and I'm happy to mentor anyone that want to push it forward.

**Comment by tbekolay** [comment]
It would be helpful for this `lesson-template` repo to have HTML pages that give some assistance to lesson maintainers that we can see at http://swcarpentry.github.io/lesson-template/ . It would be nice to have a single place where maintainers can consolidate our collective wisdom.

Another useful thing to have rendered there is an example of what all our CSS classes look like. Would make it easier to make little changes to styles.

**Comment by tbekolay** [comment]
This is a minor point that would take seconds to fix, but: I really dislike Courier New, which is the default on Linux. [Inconsolata](https://www.google.com/fonts/specimen/Inconsolata) is available through Google Webfonts and would be a good replacement.

**Comment by tbekolay** [comment]
Right now our code blocks syntax highlight based on the language. It would be helpful also if the language that the code represents was rendered somewhere too. In Python's [command-line lesson](http://swcarpentry.github.io/python-novice-inflammation/10-cmdline.html) we have a callout to say that certain code blocks are bash now; if we had the language rendered somewhere (but not too glaringly) it would make this more clear.

This could show up, e.g., in the top-right corner to the code block, without adding extra height to the blocks.

**Comment by tbekolay** [comment]
It'd be nice to check for more HTML-output-related things in our unit testing. There are tools like [html-proofer](https://github.com/gjtorikian/html-proofer) for this, but mostly I notice that when I serve the page with `python -m SimpleHTTPServer` I see a lot of 404s.

**Comment by gdevenyi** [comment]
The lesson validator should have a bit more helpful of an output explaining what's wrong and why (including snippits/arrows showing where the problem is)

**Comment by tbekolay** [comment]
Some additional tools to help lesson maintainers keep up-to-date with shared files would be nice. Some possibilities:
- Add a `make update`, which would do the necessary `git` wrangling to update the stuff in `_includes`, `_layouts`
- Have the `make update` script output a changelog, saying what's changed since last you updated (in case the lesson maintainer needs to update pages due to changes in shared files). This could either be automated and show git commit messages (in which case they need to be written with lesson maintainers in mind), or we could maintain a separate changelog that only has lesson-maintainer-specific messages.
- Host the CSS in https://github.com/swcarpentry/styles at http://swcarpentry.github.io/styles and have each lesson link to those, instead of including them in each repository

**Comment by gdevenyi** [comment]
The main lesson page should have a "cite me" section or other such information, since we now have proper publications.

**Comment by gdevenyi** [comment]
@tbekolay The issue with remote hosting of the CSS is the risk of catastrophic failure of rendering for forked lessons that don't get updated with major layout changes.

**Comment by tbekolay** [comment]
@gdevenyi How many backwards-incompatible changes get introduced in CSS? I would think that we probably already have these issues when people update because they don't actually look at the diff to know what changed.

**Comment by gdevenyi** [comment]
@tbekolay I think the problem will end up being "we don't know" If we were to introduce such a change, anything forked after that point could be broken simply by the slow drift of the CSS changes as they accumulate over time.

**Comment by ChristinaLK** [comment]
+1 to prev/next (and up) links (i might even be willing to take this on.)  
+1 to location for maintainers to store collective maintenance knowledge (how often to update html, how to resolve contentious issues/PRs, etc.)

Differentiate between "concept" exercises like multiple choice questions and "practical" exercises that involve doing something w/ the lesson data or implementing a piece of code.  

Not lesson-template, but rather repository management: each lesson has a persistent "sticky" issue, curated by maintainer, that lists current repo priorities for PRs (problem: would eventually fall to bottom of list -> could be linked in CONTRIBUTING and/or README).  Perhaps in a separate "sticky" issue, create a list of specific things that are _not_ to be changed based on previous discussions, for example, "don't submit a PR changing x to y, because we've already been over this," with a link to relevant issue and/or mailing list discussion.  
I think both of these would make contributing much more friendly + accessible, both by providing direction and preventing people from doing work that is likely to be not included.

**Comment by tbekolay** [comment]
@ChristinaLK I like this idea a lot! How about a file like `roadmap.md` in each repository? It can list basically where we've been (things that have been discussed and won't change) and where we're going (things we want people to discuss / work on).

**Comment by abbycabs** [comment]
Small suggestion:I think it would be useful to have the maintainers info for that repo in the README or CONTRIBUING.

(did not read whole thread...)

**Comment by gvwilson** [comment]
What do you have in mind for 'maintainers info'?

**Comment by abbycabs** [comment]
At the very least, who the maintainers are. Maybe a way to reach out if new contributor has a question.

I know this is all listed on the website, but it takes some digging and isn't immediately intuitive to a new contributor browsing the through the repo.

**Comment by chendaniely** [comment]
@r-gaia-cs since the lessons are already in `html` files, can we have a button that will `show all on one page`?  I'm not sure what that would entail, but that would make things much more flexible for the future?

**Comment by iglpdc** [comment]
I'm a big fan of some of the changes proposed. In particular, I'd love this:

> +1 to location for maintainers to store collective maintenance knowledge (how often to update html, how > to resolve contentious issues/PRs, etc.)

**Comment by iglpdc** [comment]
Rethink the use of the motivation slides and redesign accordingly. Are they meant to
- open the lesson,
- open the workshop, as a teaser for the things to come,
- not be used in a workshop, i.e. as an elevator pitch to hosts?

**Comment by iglpdc** [comment]
Decide what to do with the extra materials, in particular what should be in `discussion.md` and how should be written. The big risk I see is to bloat the lessons, and end up with 5-hour beasts that are impossible to teach in a workshop.

**Comment by gvwilson** [comment]
Or should we get rid of the motivation slides entirely?  Nobody seemed 
excited about creating them, and I don't know if anyone's actually using 
them.

**Comment by tbekolay** [comment]
I'm +1 removing the motivation slides. When teaching, I either ask the students why they wanted to learn this, or use my own personal experiences as a motivator. The times I've seen these motivation slides presented, it either preaches to the choir or gets people defensive.

As a practical side-effect, it would greatly reduces the burden on our shared files ;) No need for deck.js or  the slides layouts!

**Comment by iglpdc** [comment]
Keep a meta-repo of lessons. This could be simply a table with all our lessons, with links to the repos and html versions, and a short description of their intended use. E.g. (links are broken)

| Lesson | Short description | Duration | Long description |
| --- | --- | --- | --- |
| [git-novice](https://github.com/swcarpentry/git-novice) | Novice lesson on Git | 3 hours | This is part of our core curriculum |
| [shell-novice-pt](https://github.com/swcarpentry/git-novice) | Translation to portuguese of our novice shell lesson | 3 hours | This is part of our core curriculum |
| [capstone-biblio](https://github.com/swcarpentry/git-novice) | A capstone project using make | 2 hours | You can use it to close a workshop as mixes Git, Python and shell |

**Comment by iglpdc** [comment]
What about moving the slides for the core lessons to their one repo (e.g. `pitch-core-curriculum`)? If the only use is to pitch outside workshops, it makes sense that they are together.

This removes deck.js from the lessons themselves and we don't throw away the work we already have.

**Comment by gvwilson** [comment]
http://software-carpentry.org/lessons.html is meant to be the index of 
lessons.

**Comment by wking** [comment]
On Mon, May 25, 2015 at 08:18:35AM -0700, Abigail Cabunoc Mayes wrote:

> At the very least, who the maintainers are.

I think we already have a framework for this.  See #195, #223,
swcarpentry/lesson-example#2, and [1](https://github.com/swcarpentry/lesson-example/tree/aaf6da60a4750e40983c6e5afd274dd83296431e#maintainers).

> Maybe a way to reach out if new contributor has a question.

I think we have a framework for this too.  See [2,3].

**Comment by chendaniely** [comment]
Can we also add a part on how to get started on your own? Something similar to my blog post about this: http://chendaniely.github.io/blog/2015/05/05/getting-started-with-data-science/

**Comment by iglpdc** [comment]
> http://software-carpentry.org/lessons.html is meant to be the index of lessons.

Ok, but I was thinking something for instructors and hosts. Now that we have only three topics, I expect the last half-day to be fill with different capstone projects (we have some already). When building a workshop, I'd like to have, for both the instructor and the host, a place where we could see all the stuff we have available (say, a capstone project for oceanographers in R.)

I think the link above should be pointed more to the online learners and the potential hosts, and kept relatively short. While what I'm proposing should be pointed to confirmed hosts and instructors, and contain all we have (including translations.)

**Comment by tbekolay** [comment]
@wking: The fact that few of us know about these is evidence that this information needs to be put somewhere else. Most of us maintainers only know about what's in our own repositories. Any information that we think people using the lesson should know about should be in our own repositories. Information that all maintainers need to know about should also be in a single place; if it's `lesson-example` then that's fine but we should all know about it.

**Comment by wking** [comment]
On Mon, May 25, 2015 at 09:52:00AM -0700, Trevor Bekolay wrote:

> @wking: The fact that few of us know about these is evidence that
> this information needs to be put somewhere else. Most of us
> maintainers only know about what's in our own repositories. Any
> information that we think people using the lesson should know about
> should be in our own repositories. Information that all maintainers
> need to know about should also be in a single place; if it's
> `lesson-example` then that's fine but we should all know about it.

Agreed, which is why I've been suggesting standard release procedures
for this repository and the associated lesson-example (#76), with
tagged releases, lists of user visible changes, migation notes, etc.
I've also suggested we store the maintainer-oriented docs somewhere
that will show up in the downstream lesson repositories (#215).

But in this case, part of the problem is that I just haven't gotten
around to creating the per-lesson PRs I mentioned here [1](https://github.com/swcarpentry/lesson-template/issues/195#issuecomment-94358755).

**Comment by daisieh** [comment]
I'd love it if there were a simple way to generate a quick slide deck from the lessons, maybe with just the images and code snippets. Obviously most of us use live coding for the lessons, and that's fine, but I'd love for there to be a simple way for me to put up, for example, the diagrams from the Git lesson on a projector when I'm discussing those parts.

**Comment by rgaiacs** [comment]
> since the lessons are already in `html` files, can we have a button that will `show all on one page`?
> I'm not sure what that would entail, but that would make things much more flexible for the future?

Yes. My patch cover it. As I mention I just need to clean it.

**Comment by gvwilson** [comment]
What I want most is to be able to use Jekyll rather than Pandoc, but none of Jekyll's Markdown parsers seem to support styles on title lines or pre-formatted blocks.

**Comment by chendaniely** [comment]
@daisieh: I typically draw the git diagrams as I teach part by part and by the end of the 3 hours it looks like this [1].  I mostly rely on the git notes to make sure what the next command I need to cover and use the command as a prompt for my narrative while teaching.

For workshops that do not have a whiteboard, i open up one of my twitter images and refer to that picture.  This way the students see the entire concept map at once, rather than seeing separate parts.

Does that mean we should add a standardized concept map to the lessons?  One we can teach from or draw depending on resources?

[1] https://twitter.com/chendaniely/status/583689081151979520

**Comment by iglpdc** [comment]
For the record, there is a link to one of @chendaniely 's diagrams in 5.3 version of the Git instructor guide.

**Comment by daisieh** [comment]
@chendaniely: The diagrams in the lessons [1] are a bit more complex than a concept map, but serve much the same purpose. I designed them as a series that build on each other, so for those who don't want to draw as they go, they're in the lesson now, but it'd be nice if one didn't have to make a slide deck every time out of them.

[1] https://github.com/swcarpentry/git-novice/blob/gh-pages/fig/git_staging.svg

**Comment by abought** [comment]
While my initial instinct would be to suggest something tooling-related, the truth is that lessons are still evolving. I'd like to look at how our current template restrictions are working out for lesson maintainers, adding more options (eg callouts) or relaxing rules (like headings) as appropriate.

If we did add tooling, it'd be nice to prompt users for metadata up front (in a bower-style lesson build tool), and store it in a more structured format. But that might be disproportionate effort relative to the number of times it was used.

+1 to prev/next (and up) links 
+1 to initial support for translations
+1 to meta-repo for lessons (our [web page](http://software-carpentry.org/lessons.html) is a start, but doesn't always reflect works in progress, etc)

+1 to many other good ideas

**Comment by rgaiacs** [comment]
> Right now our code blocks syntax highlight based on the language.

We don't have syntax highlight. We mark the code blocks with the language
because (1) it will make our life easy in the future if we want to have syntax highlight
and (2) make clear on Markdown what the code block is.

**Comment by rgaiacs** [comment]
> - Host the CSS in https://github.com/swcarpentry/styles at http://swcarpentry.github.io/styles and have each lesson link to those, instead of including them in each repository

I and @gvwilson discussed it a lot. @gvwilson is -1 to server CSS from a third party address because this will make that to preview the lessons people needed to be connected to the internet and sometimes instructors edit the lessons on airplanes and airports.
I already suggested many alternatives/workarounds, e.g.
change the address on compilation time,
change `/etc/hosts` when needed, ...
but @gvwilson didn't like any.

If all lessons maintainers agree that server CSS from a third party address is
better we will make that change.

**Comment by abostroem** [comment]
+1 to navigation
-1 on removing the motivation slides. As a new instructor it can be helpful to see how people motivate a lesson. 
+1 to maintainers guide. Ideas to include: 
    \* merging pull requests. Is the procedure merge PR, update local copy, regenerate html, push to repo?
    \* A direct link to the lesson template slide show that explains everything (this may be an issue of making it more visible? I can never find it.
    \* The difference between the fig directory and the img directory
    \* preferred figure format and how to save an SVG file

**Comment by abostroem** [comment]
Solutions to all exercises (including an explanation of what instructors should be highlighting in each exercise). @PBarmby has already started for python

**Comment by abostroem** [comment]
I would like links in the README for the swcarpentry github page to the most used lesson repos (or currently maintained).

**Comment by rgaiacs** [comment]
> Solutions to all exercises (including an explanation of what instructors should be highlighting in each exercise).

I want to use HTML [details](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) element for this. My suggestion is write

```
> ## Challenge Title {.challenge}
>
> Description
>
>> ### Solution
>>
>> Description of solution.
```

and have a filter so that Pandoc convert it to

```
<section class="challenge panel panel-success">
<h2>Challenge Title</h2>
<p>Description</p>
<details>
  <summary>Solution</summary>
  <p>Details of solution.</p>
</details>
</section>
```

**Comment by jdblischak** [comment]
I like how the Shell and Python lessons now have an option to download the data set as a zip file. I'd like to have documentation in lesson-example for how best to do this so that all our lessons can easily provide this.

**Comment by douglatornell** [comment]
+1 to allowing sub-headings

**Comment by douglatornell** [comment]
Bring back reference guides for lessons where they are appropriate. Examples from the bc repo lessons:
- [shell](https://douglatornell.github.io/2014-09-25-ubc/novice/ref/01-shell.html)
- [mercurial](https://douglatornell.github.io/2014-09-25-ubc/novice/ref/02-hg.html)
- [python](https://douglatornell.github.io/2014-09-25-ubc/novice/ref/03-python.html)

This is perhaps not important for day-of-the-workshop use, but more so as support for the learners in the days following the workshop. Command examples and little snippets are useful memory prompt for many people.

**Comment by wking** [comment]
On Tue, May 26, 2015 at 12:47:53PM -0700, Doug Latornell wrote:

> Bring back reference guides for lessons where they are appropriate.

There's something like in references.md [1,2,3].  I'd
recommend we separate the cheat-sheets from the glossary though, since
those seem like suitably distinct ideas.

**Comment by douglatornell** [comment]
Yep, it's the cheat-sheets aspect of the bc repo reference guides that I'm advocating for, and it's totally fine with me to separate them conceptually and/or storage-wise from the reference.md file material in the present lesson structure.

**Comment by IsaKiko** [comment]
Suggested changes for MATLAB
- Include a debugging lesson
- Maybe switch functions and conditionals lessons

**Comment by gvwilson** [comment]
These comments now filed as separate issues for Version 5.4

**Comment by rgaiacs** [comment]
**Please hold any change before we have a final answer for http://software-carpentry.org/blog/2015/06/using-jekyll-for-lessons.html**.
