### ISSUE TITLE
Add next/previous links between topics and other files.

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-lesson-template#251]

**Comment by rgaiacs** [comment]
Prototype at https://r-gaia-cs.github.io/using-jekyll/01-one.html.

![screen shot 2015-06-24 at 17 56 15](https://cloud.githubusercontent.com/assets/1506457/8341299/59bbd89e-1a9a-11e5-99a7-c46a9c1de17c.png)

**Comment by gvwilson** [comment]
Good start - can you figure out how to put a list of pages in 
_config.yml in such a way that we can access that inside an HTML 
template to figure out what 'prev' and 'next' should link to?  If we 
were generating a blog, we'd get 'page.previous.url' and 'page.next.url' 
automatically, but we're not...

**Comment by rgaiacs** [comment]
> can you figure out how to put a list of pages in _config.yml in such a way that we can access that inside an HTML template to figure out what 'prev' and 'next' should link to?

Why do you want to add this list in _config.yml if we don't need it?

>  If we were generating a blog, we'd get 'page.previous.url' and 'page.next.url' automatically, but we're not...

We are talking about two different things here and I think that we need two different solutions. One for the lessons and another one for the website.

**Comment by gvwilson** [comment]
I'm thinking about the lessons - we can guess the order of 01-_.html, 
02-_.html (because they're named that way on purpose), but what about 
the non-numeric files?

**Comment by rgaiacs** [comment]
> but what about the non-numeric files?

Right now the non-numeric files are
- `index.md`,
- `reference.md`,
- `discussion.md` and
- `instructors.md`.

We can embed in the logic the order you want. After the last numeric file you want 
`reference.md` followed by `discussion.md` and `instructors.md`, correct?

**Comment by gvwilson** [comment]
I _think_ so, but now I'm curious: how do we override page.previous and 
page.next?

On 2015-06-25 4:59 PM, Raniere Silva wrote:

> ```
> but what about the non-numeric files?
> ```
> 
> Right now the non-numeric files are
> - |index.md|,
> - |reference.md|,
> - |discussion.md| and
> - |instructors.md|.
> 
> We can embed in the logic the order you want. After the last numeric 
> file you want
> |reference.md| followed by |discussion.md| and |instructors.md|, correct?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/swcarpentry/lesson-template/issues/251#issuecomment-115396668.

## 

Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org
