### ISSUE TITLE
Add solutions to all challenges.

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-lesson-template#267]

**Comment by Deborah-Digges** [comment]
I'd like to help out with this.
Which lesson would be a good one to get started with?

**Comment by rgaiacs** [comment]
> Which lesson would be a good one to get started with?

@Deborah-Digges The best one to start is the one you are interested to read. =)

**Comment by Deborah-Digges** [comment]
Thanks @rgaiacs. I'd like to get started with the  make lesson, as I've recently read it. @mikej888 I'll send in an initial PR with the solutions for the challenges if that's alright with you.

**Comment by rgaiacs** [comment]
> I'd like to get started with the make lesson, as I've recently read it.

Great. :sparkles: 

> I'll send in an initial PR with the solutions for the challenges if that's alright with you.

This is a open source project so PR are always welcome. =)

**Comment by Deborah-Digges** [comment]
This is an initial PR for the make lesson: https://github.com/swcarpentry/make-novice/pull/15

**Comment by DamienIrving** [comment]
When I'm teaching I usually tell learners to go to the lesson site to view the challenges that they need to complete. I'm therefore wondering if we could keep the answers separate from the questions, so that learners can't see the answer directly under the question in the notes?

**Comment by abostroem** [comment]
@PBarmby has already started this for the Python lessons. See https://github.com/swcarpentry/python-novice-inflammation/pull/99

**Comment by Deborah-Digges** [comment]
@DamienIrving In the make lesson, I've added the solutions to the "Other Resources" section of the lesson and they look like [this](http://swcarpentry.github.io/make-novice/solutions.html). Is this close to what you had in mind?

**Comment by DamienIrving** [comment]
@Deborah-Digges That is very much what I had in mind :smile:

**Comment by weaverbel** [comment]
I think this is a good idea. Can I please suggest that not just the right answer be provided, but also a brief explanation as to why it's right and the others are wrong? I think that would help people. But maybe the answers could be hidden until they click so they don't see the answer before engaging with the challenge?
Also sometimes there is a little ambiguity, e.g. the Jennifer coding challenge here: http://swcarpentry.github.io/g... The answer would be different depending on whether or not Jennifer had already committed her new code (the code that broke things).

**Comment by abostroem** [comment]
In the Python section many of the questions are not multiple choice. I would like to see a learning objective or goal for each exercise. What point is the lesson highlighting?

I would like to keep the answers in a separate document from the lessons.

**Comment by andreww** [comment]
For the MCQ's it would also be useful for us to try to write down what errors or misconceptions the distractors are designed to diagnose. Doing this should help us design and improve the questions, as well as help instructors work out what has not been understood by the students.

**Comment by twitwi** [comment]
I think it can be good for maintenance (keeping coherence) if we keep the solution very close to the challenge (and maybe use some styling/javascript to not show the solution in the main pages).

**Comment by iglpdc** [comment]
> I think it can be good for maintenance (keeping coherence) if we keep the solution very close to the challenge (and maybe use some styling/javascript to not show the solution in the main pages).

+1 to this. It would be awesome if we could have the source together and have the choice to separate the output.

**Comment by abostroem** [comment]
From a maintainer's perspective I think it makes a lot of sense to keep the solutions next to the challenges. From a learner's perspective/instructor's perspective I think (empirically) that students will struggle for a shorter period of time, are less likely to work out the answer on their own, and are less likely to ask the instructors or helpers for help if the solutions are immediately available. I would like a larger barrier than a collapsable solution in the lesson.

**Comment by twitwi** [comment]
I agree with not showing the solutions too easily to the learners.
We could use a “hidden” (only instructors would be told about it at first) trick, like adding `#instructor` to the URL, that would display the answers.
Maybe we can also think about folded "tips", that are accessible to the learners on demand.
