### ISSUE TITLE
Document how to create a ZIP of necessary files and where to store it

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-lesson-template#268]
Add documentation to lesson-example explaining how to create a downloadable ZIP of data files required for a particular lesson and where to archive it (so that we all do it in the same way).

**Comment by wking** [comment]
On Mon, Jun 08, 2015 at 05:31:42AM -0700, Greg Wilson wrote:

> Add documentation to lesson-example explaining how to create a
> downloadable ZIP of data files required for a particular lesson and
> where to archive it (so that we all do it in the same way).

I've recommended managing such data in it's own Git repository and
pointing folks at the “Download Zip” link GitHub shows on every
repository's homepage [1,2].  For links into previous discussion in
this vein, see [3](https://github.com/swcarpentry/shell-novice/issues/62#issuecomment-73101968).

**Comment by iglpdc** [comment]
Do you think this is better than having a data folder per repo? It's easier for the students, but I feel it would be harder to maintain as changes in the lesson materials would require changes in these repo too.

**Comment by gvwilson** [comment]
Moved to https://github.com/swcarpentry/styles/issues/51.
