### ISSUE TITLE
Have make check for recent knitr versions on R lessons

### ISSUE THREAD

**Issue by aammd** [swcarpentry/DEPRECATED-lesson-template#270]
As pointed out by @sritchie73 in swcarpentry/r-novice-gapminder#42,  presently the `MAKEFILE` doesn't check for recent versions of knitr. He has a [solution](https://github.com/sritchie73/r-novice-gapminder/commit/7d92fce8cc5f079f96d37f2a4f498832c423aba0) to this problem (from swcarpentry/r-novice-gapminder#41). However, our makefile hasn't been modified to run this script. I understand that changes to the MAKEFILE ought to happen in _this_ repository. What do you guys think of this approach? Could we make these changes, then pull them into r-novice-gapminder?

**Comment by fmichonneau** [comment]
I created a PR for this: https://github.com/swcarpentry/lesson-template/pull/271

I put the check in the Makefile with the rule to build the Rmd files such that lessons that are not R-based don't have to worry about it. If there is a better approach, don't hesitate to let me know.
