### ISSUE TITLE
Lesson Meta documentation

### ISSUE THREAD

**Issue by chendaniely** [swcarpentry/DEPRECATED-lesson-template#274]
Maybe this belongs on the website issues tab, but I propose some kind of meta documentation for people who have not attended our workshops on how to navigate the lessons.  I've had many friends come to me on 'where should I go to learn x' and I almost always direct them to SWC lessons, and give them a blurb on how to go through the installations and lessons.  I've written a blog post about it: http://chendaniely.github.io/blog/2015/05/05/getting-started-with-data-science/

**Comment by rgaiacs** [comment]
> I propose some kind of meta documentation for people who have not attended our workshops on how to navigate the lessons.

We will try to address adding "Next" and "Previous" links to our lessons before August.
