### ISSUE TITLE
Jekyll migration -- layouts migration

### ISSUE THREAD

**Issue by cboettig** [swcarpentry/DEPRECATED-lesson-template#280]
Note that the `_layouts`, `_include` etc are all currently written in pandoc style, e.g. using `$title$` instead of Liquid `{{ page.title }}`.  

Not that we use complex templating, but this is an area where Jekyll is much stronger than pandoc since the liquid syntax is much more flexible.

**Comment by gvwilson** [comment]
Yup - the https://github.com/gvwilson/using-jekyll repo's gh-pages 
branch has all of this patched.  (Didn't want to drop that into 
`lesson-template` until we were sure we wanted to go this way.)  And 
yes, Jekyll's templating may be frustrating at times, but it's a bucket 
better than Pandoc's.
