### ISSUE TITLE
Document use of update-copyright

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-lesson-template#288]
https://pypi.python.org/pypi/update-copyright/ should be mentioned in the lesson

**Comment by wking** [comment]
On Sun, Jan 10, 2016 at 11:09:40AM -0800, Greg Wilson wrote:

> https://pypi.python.org/pypi/update-copyright/ should be mentioned
> in the lesson

Just add a Makefile rule for AUTHORS so ‘make’ lists it as an
available target?

**Comment by gvwilson** [comment]
I expect 5% or less of instructors would find it that way - we should 
include a few sentences in the instructor training.

**Comment by wking** [comment]
On Mon, Jan 11, 2016 at 10:17:45AM -0800, Greg Wilson wrote:

> I expect 5% or less of instructors would find it that way…

Then maybe we need a “Maintenance” section in [1](https://github.com/swcarpentry/lesson-example) covering
lesson-maintainer workflows after the initial setup?

> … we should include a few sentences in the instructor training.

This repo is for lesson-maintainers, so instructor training doesn't
seem like the right place to me.  While most (all?) of our lesson
maintainers are also instructors, they're different skill sets, and
most instructors are not lesson maintainers (so notes about
update-copyright would just be a distraction).

**Comment by gvwilson** [comment]
But all lesson maintainers are instructors, and I hope that if we 
include more on lesson maintenance in instructor training, more 
instructors will contribute.  Dunno...

**Comment by wking** [comment]
On Mon, Jan 11, 2016 at 10:41:39AM -0800, Greg Wilson wrote:

> But all lesson maintainers are instructors…

… who mostly passed through instructor training a while ago ;).

> … and I hope that if we include more on lesson maintenance in
> instructor training, more instructors will contribute.

Sure, and I'm not opposed to a lesson-maintainer section during
instructor-training.  I just think that the primary lesson-maintainer
docs should live in this repository or lesson-example (see also #215).

**Comment by gvwilson** [comment]
Please move further discussion to https://github.com/swcarpentry/styles/issues/43
