### ISSUE TITLE
Running make unittest fails

### ISSUE THREAD

**Issue by atyre2** [swcarpentry/DEPRECATED-lesson-template#291]
On a windows machine with Windows 7, after following the instructions to setup Python using Anaconda distribution (Python 3.5.1 :: Anaconda 2.5.0 (64-bit)), and for dependencies [here](https://github.com/swcarpentry/lesson-example#dependencies). I then imported lesson-template and created a new local repository. Just to make sure I have everything working, I try running `make unittest` which fails with an error that python2 can't be found. I then cd tools and `python test_check.py` which gives a whole raft of errors like the one below. Running `make check` gives errors about missing files as it should, but then fails with the same 'CommonMark' has no attribute 'DocParser' error.

I had the same problem on a Linux VM (although that one wasn't necessarily carefully setup), and changing all instances of DocParser() to Parser() got rid of those errors, but there were other errors. I'm thinking I've got something not installed correctly. If so, then perhaps the instructions are lacking. I've poked around through the instructor training materials but not come across any installation instructions other than what I pointed to above. 

If this isn't the right place to raise this issue, please point me in the right direction. 

```
======================================================================
ERROR: test_topic_page_should_have_no_headings (__main__.TestTopicPage)
Requirement according to spec; may be relaxed in future
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_check.py", line 384, in test_topic_page_should_have_no_headings
    Some text""")
  File "test_check.py", line 30, in _create_validator
    return self.VALIDATOR(markdown=markdown)
  File "D:\atyre2\sampling-novice\tools\check.py", line 80, in __init__
    ast = self._parse_markdown(self.markdown)
  File "D:\atyre2\sampling-novice\tools\check.py", line 87, in _parse_markdown
    parser = CommonMark.DocParser()
AttributeError: module 'CommonMark' has no attribute 'DocParser'

----------------------------------------------------------------------
Ran 56 tests in 0.029s

FAILED (errors=56)
```

**Comment by justbennet** [comment]
We found this also and opened a separate issue, #299  I will add a cross-reference there, too.
