### ISSUE TITLE
inline code phrases sometimes wrap awkwardly

### ISSUE THREAD

**Issue by DanielBaird** [swcarpentry/DEPRECATED-lesson-template#296]
While looking through the shell novice lessons, a few times an inline command wrapped awkwardly.

E.g. the `p*.p?*` on the second line here wraps the asterisk to the next line:
![poor-wrap-1](https://cloud.githubusercontent.com/assets/25352/13514400/37443410-e1f4-11e5-93d1-59ebd4a867bb.png)

And the command starting with `wc` on the second line here:
![poor-wrap-2](https://cloud.githubusercontent.com/assets/25352/13514403/39124462-e1f4-11e5-8a11-c0ae1bb5292d.png)

This could be avoided by adding the css rule like `p > code { white-space: nowrap }`, which would forbid line breaks inside code samples, but only when they're within paragraphs.

If this sounds like a good idea, let me know and I'll submit a pull req adding that CSS rule to the template CSS.

A reason to not fix: the lessons I've seen usually use short inline code samples; if there are lessons with lots of long code samples, preventing wrap within code will lead to erratic line lengths.

**Comment by gvwilson** [comment]
Please add - we can use all the help we can get with our CSS.

**Comment by twitwi** [comment]
I agree. Please make a pull request.
If inline code is too long, it probably shouldn't be inline.

**Comment by DanielBaird** [comment]
I've submitted pull req #297 to update the lesson template.  Is there a way to retro-fit the fix to existing lessons?  If there's no automated system, I can make the same change to each core lesson (or at least add it to my to do list...)

**Comment by wking** [comment]
On Sun, Mar 06, 2016 at 08:14:38PM -0800, Daniel Baird wrote:

> I've submitted pull req #297 to update the lesson template.  Is
> there a way to retro-fit the fix to existing lessons?  If there's no
> automated system, I can add the same change do each core lesson (or
> at least add it to my to do list...)

I don't see any references to the repository in the current
lesson-template or lesson-example content, but at least as of 600c4344
(Merge branch 'master' of github.com:swcarpentry/styles into core,
2015-03-21, #206) the CSS and generic JavaScript was being maintained
in [1](https://github.com/swcarpentry/styles).  If that's still the case, #297 should probably be directed at
that repo.

But the end result will be an update in this repository (either
directly, or by a later merge of swcarpentry/styles), and downstream
lessons should be able to update by merging this repo (e.g. see
swcarpentry/shell-novice@eaf8deb1, Merge branch 'gh-pages' of
github.com:swcarpentry/lesson-template into gh-pages, 2015-06-15,
swcarpentry/shell-novice#111).

**Comment by DanielBaird** [comment]
Ah, I didn't see that other repo.. I'll re-do my pull req against that.

I won't close this for now, in case it turns out merging from the styles repo is problematic. But I'm okay with it being closed by someone who knows for sure.

**Comment by wking** [comment]
On Mon, Mar 07, 2016 at 03:24:59PM -0800, Daniel Baird wrote:

> Ah, I didn't see that other repo.

Docs for this sort of distributed maintenance would be nice.  Linux
has [1](https://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/tree/MAINTAINERS?id=refs/tags/v4.4.4#n69).  We're not that big or complicated, but some notes in the
repository that clarify the upstream repo for each file/directory/…
would make this easier on new contributors.  I'm happy to PR something
like that if the lesson-template maintainers want.
