### ISSUE TITLE
CSS for print need fix

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/DEPRECATED-lesson-template#298]
Some pages of Shell lesson (Git commit c5dbc971a71d5eb2a8d1ada7a5a83aa71f08a92e and da3693b4df2f0dc48b2d8bb7bb13b59d4c0b41ec) when print:

![software carpentry_ the unix shell1](https://cloud.githubusercontent.com/assets/1506457/14051425/a3abd24e-f2ba-11e5-9076-bce5289a7ed7.jpg)

![software carpentry_ the unix shell2](https://cloud.githubusercontent.com/assets/1506457/14051426/a63f275e-f2ba-11e5-8020-fecc4e3bf68d.jpg)

This isn't how https://github.com/swcarpentry/instructor-training/ looks.

@gvwilson I couldn't follow all your experiments with the lesson-template that you already push to https://github.com/swcarpentry/instructor-training/. I'm happy to help if you could give me a overview of the changes.

**Comment by gvwilson** [comment]
Please move further discussion to https://github.com/swcarpentry/styles/issues/42
