### ISSUE TITLE
make clean should clean .html files

### ISSUE THREAD

**Issue by justbennet** [swcarpentry/DEPRECATED-lesson-template#300]
I think it is usual for make clean to clean generated object and binary files created by make.  The clean rule in the Makefile accompanying lessons doesn't do that.  Shouldn't the clean rule clean the .html files?

This seems more necessary since git clone, unlike tar, does not preserve time stamps on files cloned from github.  That means that every fresh clone will have fully up-to-date .html files, so no changes incorporated into .md files in the repository after the last push of .html files there will be incorporated into a local make.

Perhaps the editor backup files would be better added to .gitignore?  Or, perhaps the current 'clean' rule could be renamed 'tidy'.

**Comment by gvwilson** [comment]
We're no longer committing the HTML (yay!).
