### ISSUE TITLE
make check

### ISSUE THREAD

**Issue by justbennet** [swcarpentry/DEPRECATED-lesson-template#301]
It appears that at least one group wants to include callouts for {.callout} and for {.challenge} in the instructor.md and discussion.md files.  The examples I found were in the git-novice lesson.  That causes make to throw an error:

```
$ make check
python tools/check.py .
ERROR: In ./discussion.md: Found callout box with unrecognized style 'callout'
ERROR: In ./instructors.md: Found callout box with unrecognized style 'challenge'
WARNING: 2 errors were encountered during validation. See log for details.
make: *** [check] Error 2
```

I will file a PR to tools/check.py to fix that.

**Comment by gvwilson** [comment]
Please hold off on any major surgery to the tools until the maintainers 
have had a chance to decide on what the next round of fixes to the 
templates will be - I hope they'll make many of these problems go away.

**Comment by carpenterbennet** [comment]
No worry, there, I'm not up to major surgery.  The fix was very quick and is submitted.  If it gets superceded, nothing lost.

**Comment by gvwilson** [comment]
We've rewritten `tools/check.py` to conform to the new template.
