### ISSUE TITLE
Should validator check maximum width of markdown files?

### ISSUE THREAD

**Issue by gdevenyi** [swcarpentry/DEPRECATED-lesson-template#305]

**Comment by gvwilson** [comment]
1.  Please move this to the `styles` repository - we're going to be 
   doing away with `lesson-template`.
2.  `make lesson-check-all` runs `bin/lesson_check.py` with extra flags 
   to check line lengths.

**Comment by gdevenyi** [comment]
Thanks, missed that the 2016-06 branch has all the new stuff.

Resolved anyways, maximum width checking is implemented.
