### ISSUE TITLE
Apply CSS based on id instead of class

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/DEPRECATED-lesson-template#32]
Related with #25.

Since Pandoc sets id attribute for headers:

```
$ cat sample.md 
## Prerequisites
$ pandoc -t html sample.md  
<h2 id="prerequisites">Prerequisites</h2>
```

what about use

```
#prerequisites {
    ....
}
```

instead of

```
.prerequisites {
    ....
}
```

in our CSS? This will avoid some post processing.

**Comment by aaren** [comment]
@r-gaia-cs it would be easy to modify the filter to set the class based on the title, i.e. remove the need to specify a class in the blockquote header. 

Then a blockquote that begins with '## Prerequesites` (or some other permitted title) gets turned into a div with class 'prerequestites'.

Note that you can set the id of the header to whatever you want, e.g.

```
## Prerequesites {#different_id}
```

becomes

```
<h2 id="different_id">Prerequisites</h2>
```

**Comment by rgaiacs** [comment]
@aaren Thanks.

I'm closing this based on @aaren's comment and because I forgot that we want a style for all the section and not only for the title.
