### ISSUE TITLE
Design of lesson validation tool.

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-lesson-template#34]
Please use this issue for discussion of design of a lesson validation tool (`tools/check`).

**Comment by abought** [comment]
I've also been working on an independent validation tool; please let me know if there are features worth combining. https://github.com/abought/lesson-template/tree/gh-pages/tools 

Validation of the markdown does make the most sense, as it allows us to change the HTML template without rewriting the validator. (content separate from presentation) 

Raniere's tool is based on the raw markdown text (easier handling of nested content), while mine is based on the CommonMark parser (more tolerant of equivalent markup, and slightly easier to treat blocks of content as one piece).

**Comment by gvwilson** [comment]
Whoa - can you please PR this so we can bring it into the 
lesson-template repo and start merging with @r-gaia-cs's stuff? This is 
awesome...
Thanks,
Greg

**Comment by rgaiacs** [comment]
Close since this was covered in #35.
