### ISSUE TITLE
converting blockquotes to div

### ISSUE THREAD

**Issue by aaren** [swcarpentry/DEPRECATED-lesson-template#4]
Where is the code that does the blockquote-div post-processing? Is that something that you need writing?

In the README:

> One final note: we try not to put HTML inside Markdown because it's ugly to read and write, and  error-prone to process. Instead, we put things that ought to be in <div> blocks, like the learning objectives and challenge exercises, in blocks indented with >, and do a bit of **post-processing** to attach the right CSS classes to these blocks.

**Comment by gvwilson** [comment]
Yes, the post-processor needs to be written - if you'd like to help us 
get started, please mail me (gvwilson@software-carpentry.org) and I'll 
fill you in.
