### ISSUE TITLE
[check] Report problem with links to local files that aren't HTML

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/DEPRECATED-lesson-template#40]
**Related with** #34 and #35.

If I make the following change:

```
diff --git a/pages/01-one.md b/pages/01-one.md
index 9857e50..589e987 100644
--- a/pages/01-one.md
+++ b/pages/01-one.md
@@ -33,7 +33,7 @@ and possibly including:

 or an image from the `figs` directory:

-![this is the image's title](fig/example.svg "this is the image's alt text")
+![this is the image's title](fig/exemple.svg "this is the image's alt text")

 > ## Challenge Title {.challenge}
 >
```

and run our validator

```
$ git rev-parse HEAD
0323e1c50d35a5743cf3a9c454248a49cebdf3f2
$ python tools/validate_markdown_template.py pages/01-one.md 
INFO:root:Beginning validation of pages/01-one.md using template topic
INFO:root:File pages/01-one.md successfully passed validation
INFO:root:All Markdown files successfully passed validation.
```

No error was reported about the broke link.

**Comment by abought** [comment]
@r-gaia-cs : Thanks; I was not aware of this requirement. Currently it only validates that local html links have a matching Markdown file. 
1. What other links must be validated? (is "any other local file" sufficient?)
2. In cases where it links to a file, are there any restrictions on asset location? (the validator needs to know where to look relative to the file being examined)

For a first pass, I will implement assume that the path given is relevant to the lesson parent directory. (assumed to be ../<path> relative to the markdown file being validated) Let me know if that needs refinement.

**Comment by rgaiacs** [comment]
> 1. What other links must be validated? (is "any other local file" sufficient?)

Yes. Any other local file. E.g.
1.  Link to another HTML.
   
   ```
   Text [link](local-address.html) more text.
   ```
2.  Link to another HTML with position
   
   ```
   Text [link](local-address.html#keyword) more text.
   ```
   
   This one you can leave for know. I need to talk with Greg about the
   glossary.
3.  Link to non-HTML file.
   
   ```
   Use [this CSV](data.csv) for the exercise.
   ```
4.  "Inline" figures.
   
   ```
   Text ![symbol](figure.svg) more text.
   ```
5.  "Float" figures.
   
   ```
   One paragraph.
   
   ![symbol](figure.svg)
   
   Another paragraph.
   ```

> 1. In cases where it links to a file, are there any restrictions on asset location?

All the links should be relative.

Thanks.

**Comment by abought** [comment]
I've added validation for the above requested items, and unit tests for the specific strings you indicated above. It now checks local file links as well as images.

If *.html, it checks that there is a corresponding markdown file in the same folder as the document being validated. If the path is anything else, it checks that the file exists in that path relative to the document root. Web links are ignored.

We can keep this open pending @gvwilson comments on how to handle anchor links (eg for glossary). Let me know if I missed any other linked content cases.

**Comment by rgaiacs** [comment]
Close since this was covered in #35.
