### ISSUE TITLE
[check] Report problem with wrong heading level

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/DEPRECATED-lesson-template#41]
**Related with** #34 and #35.

If I make the following change:

```
diff --git a/pages/01-one.md b/pages/01-one.md
index ca4dc26..e4b290f 100644
--- a/pages/01-one.md
+++ b/pages/01-one.md
@@ -4,7 +4,7 @@ title: Lesson Title
 subtitle: Topic Title One
 minutes: 10
 ---
-> ## Learning Objectives
+> # Learning Objectives
 >
 > * Learning objective 1
 > * Learning objective 2
```

and run our validator

```
$ git rev-parse HEAD
0323e1c50d35a5743cf3a9c454248a49cebdf3f2
$ python tools/validate_markdown_template.py pages/01-one.md
INFO:root:Beginning validation of pages/01-one.md using template topic
INFO:root:File pages/01-one.md successfully passed validation
INFO:root:All Markdown files successfully passed validation.
```

No error was reported about the wrong heading level.

**Comment by abought** [comment]
This example fixed in head: mandated that Prerequisites block (index.md) and Learning Objectives block (topic pages) have a level 2 heading.

Followup question for @r-gaia-cs : should other document headings also always be restricted to level 2?

Are there documents where a different heading level is either allowed, or preferred? (eg, discussion.md is fairly free-form)

**Comment by rgaiacs** [comment]
> This example fixed in head: mandated that Prerequisites block (index.md) and Learning Objectives block (topic pages) have a level 2 heading.

Thanks.

> Followup question for @r-gaia-cs : should other document headings also always be restricted to level 2?

From Greg's design of how lessons should be, each file `[0-9]{2}-.*\.md`
**must** be cover in 10-15 minutes so authors probably don't need heading except
for Learning Objectives, Call out box, ...

So, I'm OK that the validate check that all headings are level 2. If you prefer,
check that at least they are >= 2.

> Are there documents where a different heading level is either allowed, or preferred? (eg, discussion.md is fairly free-form)

For `discussion.md` you can only check if headings are >= 2.

**Comment by abought** [comment]
Sounds like simple (and predictable) is the best option- thanks for the insight. The validator now checks that all headings are exactly level 2.

**Comment by rgaiacs** [comment]
Close since this was covered in #35.
