### ISSUE TITLE
Links in footer are incorrect

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-lesson-template#52]
1.  The GitHub link in the footer should point to the lesson's repo, not to a generic repo.
2.  The Bug Report link in the footer should point to the lesson's issue tracker, not email.

Fixing these probably means adding a configuration variable somewhere that is the URL of the GitHub repository...

**Comment by aaren** [comment]
I think we can avoid configuration here: assuming that users follow the setup instructions, they will have their github repo labeled as 'origin' (see point 4 of manual setup in readme). We can then capture the url for 'origin' in the makefile and inject this as a variable in the footer.

Shall I implement this?

**Comment by gvwilson** [comment]
Happy to look at an implementation...

**Comment by gvwilson** [comment]
A better solution is to add a check to the validator.

**Comment by gvwilson** [comment]
Can we please add a check to the validator to make sure the footer link points to the right repo?

**Comment by abought** [comment]
> Can we please add a check to the validator to make sure the footer link points to the right repo?

Can someone confirm how we are currently determining repo location? #97 seems closed, and I'm not seeing, eg, a config.yml file.

**Comment by gvwilson** [comment]
I shell 'git remote -v' and find the line with 'origin' and 'fetch' and 
extract the URL.  Clumsy but effective, and doesn't require any 
Python-Git libraries.

**Comment by rgaiacs** [comment]
> Can someone confirm how we are currently determining repo location?

I prefer add something to `Makefile` because `git remote -v` will not work for me since I have only one directory named `lessons` with all our lessons.

**Comment by abought** [comment]
If we're basing it on remote names, we may want to defer this until the move to a single known build environment (eg jekyll on github) is done. Not everyone is guaranteed to name their remote `origin`, which could lead to bad links being committed when people rebuild HTML locally.

(Actually, I name my SWC remote `upstream` and my fork `origin`. So, yeah...)

Otherwise, can have validator check `_includes/footer.html`.
