### ISSUE TITLE
Keep gh-pages for output only

### ISSUE THREAD

**Issue by aaren** [swcarpentry/DEPRECATED-lesson-template#6]
Rather than using `gh-pages` for development _and_ for storing the generated site, how about we spilt these two functions?

Here's the workflow:
1. new repo on github
2. add lesson-template as remote
3. pull template to `master`
4. write some lessons on `master`
5. `make pages`
6. git push origin gh-pages

I'm suggesting modifying the pages recipe in the Makefile to 
1. make the site in a .gitignored directory (pages/_site or something)
2. copy the contents of that directory to the gh-pages branch

here is a hacky example:

``` make
html_build=pages

html:
    # content of this is like the old pages recipe 
    # except outputs to pages/_site

pages: html
    @echo "Building gh-pages..."
    @root_dir=$$(git rev-parse --show-toplevel) && \
    tmp_dir=$$(mktemp -d) && \
    cd $${tmp_dir} && git init --quiet && \
    git remote add origin $${root_dir} && \
    git pull --quiet origin gh-pages && \
    git rm -rf --cached --quiet * && \
    rsync -a $${root_dir}/${html_build}/_site/ . && \
    git add -A && git commit --quiet -m "update gh-pages" && \
    git push --quiet origin master:gh-pages
```

Then I'd suggest that we bring the `Makefile` to the top-level.

**Comment by gvwilson** [comment]
Thanks for the suggestion - we discussed this, and variations on it, and decided that having everything in one branch would be simpler and more reliable for most of our instructors.
