### ISSUE TITLE
Adding motivation slides using deck.js.

### ISSUE THREAD

**Issue by twitwi** [swcarpentry/DEPRECATED-lesson-template#60]
I'd like to rebase/clean/prepare my branch for a pull request. The branch implements deck.js slides for motivation.md, with a software carpentry theme, at the suggestion of @gvwilson.

A few questions arise:
1. as it touches motivation.md, should I rebase it against gh-pages?
2. corollary, what is the "core" branch?
3. any thoughts on whether the default motivation slides should contain a) a minimal content (like in the current gh-pages), b) the overall software carpentry motivation, or c) a tutorial on how to write the content.

http://twitwi.github.io/lesson-template/motivation (will be updated) currently shows a mix of b) and c).

**Comment by twitwi** [comment]
http://twitwi.github.io/lesson-template/motivation is now the rebased version which loads faster.
It still shows the content mentioned above.

**Comment by twitwi** [comment]
Note: just rebased the branch + add the title page by default, use the "omit-title" header not to add it.

**Comment by gvwilson** [comment]
Where does omit-title go?

**Comment by twitwi** [comment]
This needs to go in the yaml header. This (title slide addition) only applies to the slides written in .md and converted with pandoc.

**Comment by gvwilson** [comment]
Ah - OK, I'm writing HTML directly.

**Comment by twitwi** [comment]
Note: http://twitwi.github.io/lesson-template/motivation has been updated to use the "revealjs" generator (just a pandoc slide deck generator).

Related pull requests: https://github.com/swcarpentry/lesson-template/pull/128 https://github.com/swcarpentry/lesson-template/pull/129 by @r-gaia-cs

**Comment by gvwilson** [comment]
Is this one still active?

**Comment by twitwi** [comment]
This can be closed as @r-gaia-cs imported my changes in https://github.com/swcarpentry/lesson-template/commit/e22aa93637d9ca8aad4657cf1252a541c7a4dea1
