### ISSUE TITLE
Lesson versioning

### ISSUE THREAD

**Issue by DamienIrving** [swcarpentry/DEPRECATED-lesson-template#62]
This discussion started on the discuss email list. I'll include relevant snippets from that discussion below...

**Comment by DamienIrving** [comment]
@DamienIrving initiated with:

> Now that the new lesson template is available, there are lots of really cool lessons popping up. I'm wondering whether it would be worth somehow labeling these repos with a status? For instance, the python-novice-inflammation lesson is pretty much complete and ready to go, while the python-novice-tutles lesson is still very much under construction (as far as I can tell). Workshop organisers and instructors will no doubt be browsing all our repos to find the best lessons for their workshop, so it would be very useful for them to know the status of what they're looking at.
> 
> Come to think of it, what would be really great is a consolidated lesson catalogue that self-updates when new lesson repos are added and/or their status changes. This would be great not only for workshop organisers/instructors, but also people looking to contribute to our lesson materials.

**Comment by DamienIrving** [comment]
@cboettig followed with:

> Perhaps Github tags/releases would be one way for lesson developers to indicate that the lessons in a particular repo were ready for release vs still being actively flushed out?

**Comment by DamienIrving** [comment]
@wking suggested:

>  I'd recommend folks use semantic versioning [1] with 1.0.0
> releases when they think the lesson is ready to go.  Then we could
> have an index (swcarpentry/lesson-index?) with a script that checked
> the GitHub API to print the most recent release for each lesson in a
> table:

`<lesson name>  <latest release>  <date of that release>`

> The only information we'd need to register a lesson would be the
> GitHub repository (e.g. swcarpentry/hg-novice), and we could expand
> the script to support non-GitHub hosting if we get demand.

**Comment by DamienIrving** [comment]
and finally I responded with:

> - In choosing version numbers we'd have to be careful not to confuse people, since the current materials up on the main website are labelled collectively as "Version 5" (I'd say our collection of lessons is so large now that individual lesson versioning is more appropriate than collective versioning - we'd just have to explain that to people)
> - As well as `<lesson name>, <latest release> and <date of that release>`, it might be nice to hook that catalogue up with the instructor survey responses so we can give an indication of how many times the lesson of that name has been used at a workshop (i.e. so people browsing can get a sense of which are the lessons that people usually use)

**Comment by wking** [comment]
On Mon, Dec 15, 2014 at 05:36:45PM -0800, Damien Irving wrote:

> and finally I responded with:
> 
> > - As well as `<lesson name>, <latest release> and <date of that
> >   release>`, it might be nice to hook that catalogue up with the
> >   instructor survey responses so we can give an indication of how
> >   many times the lesson of that name has been used at a workshop
> >   (i.e. so people browsing can get a sense of which are the lessons
> >   that people usually use)

Will those be published publically somewhere?  I'm happy to write up
the script to build this site, but I don't have the permissions to
create swcarpentry/lesson-index.

**Comment by gvwilson** [comment]
@DamienIrving can we close this one?

**Comment by DamienIrving** [comment]
@gvwilson It was never really addressed. If I scroll through the repos at https://github.com/swcarpentry and come across https://github.com/swcarpentry/python-novice-turtles for instance, I have no way of knowing whether it's a mature lesson that has been used in over 200 workshops or one that people are working on but has never actually been used in a workshop.

I still think we probably need a system for indicating this information to people, even if it is as simple as a traffic light red for under construction / has never been used in a workshop, yellow for used in < 5 workshops, or green for used in > 5 workshops.

**Comment by gvwilson** [comment]
Gotcha - I thought the list on 
http://software-carpentry.org/lessons.html was enough, but hadn't 
thought of people looking up lessons on GitHub.  There doesn't appear to 
be a built-in way to label repositories on GitHub (like Flickr image 
tags) - you know of anything else that would show up on GitHub itself?

**Comment by wking** [comment]
On Sun, Jun 07, 2015 at 03:33:13AM -0700, Damien Irving wrote:

> I still think we probably need a system for indicating this
> information to people, even if it is as simple as a traffic light
> red for under construction / has never been used in a workshop,
> yellow for used in < 5 workshops, or green for used in > 5
> workshops.

Do we collect stats on how frequently a particular lesson has been
taught.  Or how much the instructor customized it?  The former is
probably [1](https://github.com/swcarpentry/lesson-template/issues/62#issuecomment-67099131), but the latter may be difficult to track.

For this sort of maturity information, change logs with release dates
and release notes are useful.  For example [2](https://github.com/swcarpentry/git-novice/releases) shows that there's only
a single release for the git-novice lesson, which means it's hard to
estimate how mature it is.  Once we get a handful of releases for a
given lesson, folks can skim over the release notes to get a feel for
whether the changes are high-gloss polishing, major refactoring, or
somewhere in between to get a measure of the lesson's maturity.  Note
that maturity/stability may decrease after a major 6.0 rewrite, which
may address some major architectural issue in the lesson but introduce
a lot of typos or locally-rough spots.

**Comment by DamienIrving** [comment]
@gvwilson No, I don't know of any way to label it directly on GitHub (it would be nice if there were labels like for GitHub issues).

Perhaps we should just have some standard language that gets added to `index.md`? It could be: 
- `lesson status = construction phase (not yet ready for use at a workshop)`
- `lesson status = trial phase (we are looking for instructors to trial this lesson at a workshop)`
- `lesson status = mature (appropriate for use in a workshop)`

This approach doesn't rely on usage statistics (which I think is good), nor does it rely on lesson browsers to understand any semantic versioning system that we're using (I'm not against semantic versioning, I just think that it might not be the clearest way to indicate the maturity of a lesson to a casual browser of our materials).

**Comment by gvwilson** [comment]
A suggestion made a while back was to have a header value in `index.md` 
for status, and use that to (for example) colorize the background of the 
page using CSS.

**Comment by gdevenyi** [comment]
+1 for adding a colorize tool in the CSS, this would be obvious on any page someone views. This would also put the control in the hands of the author for when they think "its ready".

If this were implemented the questions I have are:
- what is the default colour for the css, should be be "not ready" until a switch is flipped?
- should the lesson-template be set to default "not ready"
