### ISSUE TITLE
Checking links

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-lesson-template#63]
`make preview` should automatically check internal links in the generated HTML files.

**Comment by abought** [comment]
The validator does  currently check links to local files in the source markdown. 

Would you like to see the same tests done on the HTML output, or something else? Can you provide an example of links that would be present (and broken) in the HTML, but not the markdown?

**Comment by gvwilson** [comment]
1.  Clone git@github.com:swcarpentry/shell-novice.git
2.  `python tools/check`
3.  The output doesn't report the links in `index.md` to 
   `motivation.html` and `discussion.html` as broken.

**Comment by rgaiacs** [comment]
This is related with #58.

**Comment by rgaiacs** [comment]
After apply #58 to git@github.com:swcarpentry/shell-novice.git

```
$ python tools/check index.md
ERROR:root:In index.md: The document links to motivation.html, but could not find the expected markdown file mot
ivation.md
ERROR:root:In index.md: The linked page reference.html exists, but the link text 'Reference Guide' does not matc
h the (sub)title of that page, 'Shell Reference'.
ERROR:root:In index.md: The document links to discussion.html, but could not find the expected markdown file dis
cussion.md
WARNING:root:Some errors were encountered during validation. See log for details.
```

I will merge it tomorrow.

**Comment by abought** [comment]
Both of these error messages look appropriate to me with this new version. Thanks for running this, @r-gaia-cs .

**Comment by gvwilson** [comment]
+1 to merge.

**Comment by rgaiacs** [comment]
I'm closing this since it was solve.
