### ISSUE TITLE
CSS needs a complete overhaul

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-lesson-template#64]
The current display of lessons is pretty ugly - the CSS (and the classes embedded in the lessons' HTML) need to be overhauled.

**Comment by rgaiacs** [comment]
> The current display of lessons is pretty ugly - the CSS (and the classes
> embedded in the lessons' HTML) need to be overhauled.

@gvwilson If you have a list of suggestions will be easy to get something.

**Comment by gvwilson** [comment]
If I knew enough to know how it should look, I'd be writing the CSS :-)  
I think what we really need is someone with a decent eye for design.  
@jiffyclub, can we steal the look of your ipythonblocks site?

**Comment by jiffyclub** [comment]
Sure, copy whatever you like. There's not a lot to ipythonblocks.org, so you'll likely need to make some stuff up too. The code for ipythonblocks.org is at https://github.com/jiffyclub/ipythonblocks.org/tree/master/app. CSS files are under `static/`, templates are under `templates/`.

**Comment by rgaiacs** [comment]
@fmichonneau Could you give us a update of the progress of this issue? **Sorry that I lost track of it.**

**Comment by fmichonneau** [comment]
Considering this done. Please open issues if you notice anything wrong with the new CSS.
