### ISSUE TITLE
Change license to CC BY 4.0

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-lesson-template#67]
Upgrade license to CC BY 4.0 (currently CC BY 3.0) in the `core` branch; @gvwilson will then push the change to lesson repositories.

**Comment by rgaiacs** [comment]
`lesson-template` already use CC BY 4.0.

```
% g show -s 7d018cca
commit 7d018ccab9b2ea25c3478788a6b0bfc899007395
Author: W. Trevor King <wking@tremily.us>
Date:   Wed Oct 22 08:20:15 2014 -0700

    LICENSE.md: Bump the CC BY 3.0 to 4.0

    Titles from the v4 release notes [1]:

    * A more global license
    * Rights outside the scope of copyright
    * Common-sense attribution
    * Enabling more anonymity, when desired
    * 30-day window to correct license violations
    * Increased readability
    * Clarity about adaptations

    [1]: https://creativecommons.org/version4
```

https://github.com/swcarpentry/shell-novice/ also [use CC BY 4.0](https://github.com/swcarpentry/shell-novice/blob/gh-pages/LICENSE.md).

@gvwilson I believe that you already push the CC BY 4.0 for the new lesson repositories but you need to check it.

**Comment by rgaiacs** [comment]
I'm closing this since all lessons from Version 5.3 are using CC BY 4.0.
