### ISSUE TITLE
Add git pre-commit hook

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/DEPRECATED-lesson-template#69]
I would like to add a git pre-commit hook to this repository to
1. run `tools/check` before each commit to make sure that pull request follow our template and
2. verify that the `*.html` version of the changes on `*.md` was add.

The hook will not change the workflow of our contributors and it is **opt-in** (contributors will need to copy `hooks/pre-commit` to `.git/hooks/pre-commit`.

Comments?

**Comment by richford** [comment]
PR #243 addresses this issue. However, I didn't add anything to run `tools/check` before each commit. Would love to get more feedback, though I realize this is a deferred enhancement so it might have to wait until the next release.

**Comment by gvwilson** [comment]
We have a working validator again - can you please look at setting up Travis-CI for each lesson repo?

**Comment by gvwilson** [comment]
Superseded by https://github.com/swcarpentry/styles/issues/86
