### ISSUE TITLE
Add CONTRIBUTING.md File

### ISSUE THREAD

**Issue by jiffyclub** [swcarpentry/DEPRECATED-lesson-template#73]
A [CONTRIBUTING.md](https://github.com/blog/1184-contributing-guidelines) file is a good place to put style and conduct recommendations for contributors. The [bc repo has one](https://github.com/swcarpentry/bc/blob/gh-pages/CONTRIBUTING.md) that might be useful as a template.

**Comment by gvwilson** [comment]
See #170.

**Comment by rgaiacs** [comment]
Done at #170 and #174.
