### ISSUE TITLE
Release procedure for this repository

### ISSUE THREAD

**Issue by wking** [swcarpentry/DEPRECATED-lesson-template#76]
We've been having this conversation in a [number](https://github.com/swcarpentry/lesson-template/issues/48#issuecomment-66703654) of [places](https://github.com/swcarpentry/workshop-template/issues/8#issuecomment-67672413), so I'm consolidating it here.  When we make major changes to this repository (or sufficient smaller changes pile up), how will downstream repositories know about it?  Possible approaches so far:

a. @gvwilson just [launches the pulls himself](https://github.com/swcarpentry/workshop-template/issues/8#issuecomment-67633753)
b. The lesson-template maintainers run a [script](https://github.com/swcarpentry/workshop-template/issues/8#issuecomment-67697308) that opens “pull from lesson-template” issues on lessons within the swcarpentry namespace.
c. We make a release tag ([or branch?](https://github.com/swcarpentry/lesson-template/issues/48#issuecomment-66705411)) for the new release, summarize the changes in some release notes, and [publish them to likely places](https://github.com/swcarpentry/lesson-template/issues/48#issuecomment-66714220).

These are not mutually exclusive, so we can pick more than one.  We should pick at least one though ;).  Pros and cons to each approach:

a+: It gets done quickly
a-: @gvwilson has a lot on his plate already
a-: lesson maintainers might have reasons they want to wait on pulling, so we should be consulting them first

b+: it gives folks a consistent place to check and see if the merge has taken place for a given lesson.
b+: maintainers should be watching for new issues on their repositories, so they'll hear about the changes
b-: it doesn't catch lesson maintainers who aren't in the swcarpentry namespace, unless the lesson-template maintainers field and process add/remove requests from other downstream lessons

c+: this is how everybody else versions packages ;)
c+: it's easy to go back through the release notes to see what's changed if you're going to be bumping your lesson across a few lesson-template releases at once
c-: if lesson maintainers refuse to listen at any of the likely places (including a [release Atom feed](https://github.com/swcarpentry/workshop-template/issues/8#issuecomment-67672413)), they might not hear about the releases.

Personally, I'm in favor of doing at least (c).  I'm against (a) because it fuzzes out maintainer responsibilities (I'd be fine with @gvwilson running the merge for lessons where he's explicitily a maintainer, but drive-by pulls make me jumpy ;).  I'm agnostic about (b), but I think it's superflous once we're doing (c).  If I were a lesson-template maintainer, I would certainly not be excitited about maintaining a list of downstream consumers interested in getting issues created for every release.

But just because I'm in favor of (c) doesn't mean the lesson-template maintainers are ;), and this is really up to them.  Other thoughts?  Options?  What's our plan for this going to be?

**Comment by wking** [comment]
This is similar to #62, but that's about versioning the lessons themselves (which depend on this repository), while this issue is about versioning this repository.

**Comment by rgaiacs** [comment]
I'm +1 to (c) with optin for (b).

**Comment by gvwilson** [comment]
I'll organize a conference call in the week of Jan 12-16 so that 
interested parties can discuss versioning, release management, and DOIs.

**Comment by gvwilson** [comment]
Which bits of this should go into the README for this repo?

**Comment by wking** [comment]
On Sun, Jun 07, 2015 at 03:23:51AM -0700, Greg Wilson wrote:

> Which bits of this should go into the README for this repo?

I've argued for a stub README in this repository, with _all the docs_
for the template in a subdirectory (#215).  So that's how I'd
recommend handling this too.  There may be both
lesson-template-maintainer and lesson-template-consumer
(i.e. lesson-maintainer) versions of the “how to handle
lesson-template releases” docs, in which case I'd just put them in
different files under doc/template.
