### ISSUE TITLE
Add a link in README.md to this repository

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-lesson-template#78]
Every actual lesson's README.md should have a link back to this repository's README.md to help people find the instructions on formatting tools, checking and building, etc.  That link should go into the starter README.md, and the validator tool should check for it.

**Comment by peterjc** [comment]
I was about to file this issue, having realised that the individual lessons do not explain `make preview` or the dependencies.

**Comment by peterjc** [comment]
PR #80 covers this, but the existing lessions still need to be updated, so I suggest we keep this issue open till that is done.

**Comment by peterjc** [comment]
See also:
https://github.com/swcarpentry/sql-novice-survey/commit/daec2b47c63abf599283f990edc3c3a68338d270
https://github.com/swcarpentry/shell-novice/commit/375ba558183b2bfa68d095eb3b0e2d23af705efa
https://github.com/swcarpentry/r-novice-inflammation/commit/f7e645af1a181930fb5af42dc558b02ecfb16bdf
https://github.com/swcarpentry/python-novice-turtles/commit/fcddd266d3b7b3769263ac7718990c3ad363c9a0
https://github.com/swcarpentry/python-novice-inflammation/commit/69f20735db978734b553d0f23bc59334247064b7
https://github.com/swcarpentry/matlab-novice-inflammation/commit/a0e8ce7c8736d38fbe9eb63ed2d1a1afcfdb4b5f

I think we can close this issue now.
