### ISSUE TITLE
Validator should error user for missing class

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/DEPRECATED-lesson-template#89]
When use

```
> ## Challenge Title
>
> Description of a single challenge.
> There may be several challenges.
```

instead of

```
> ## Challenge Title {.challenge}
>
> Description of a single challenge.
> There may be several challenges.
```

the validator should show a error.

**Comment by gvwilson** [comment]
But how will it know?  Simplest rule would be that all blockquotes with 
titles must have classes on the titles (right now 'challenge' or 'callout').

**Comment by rgaiacs** [comment]
> Simplest rule would be that all blockquotes with titles must have classes on the titles (right now 'challenge' or 'callout').

+1

I also would like to use

```
> ## Learning Objectives {.objectives}
```

instead of

```
> ## Learning Objectives
```

to avoid problems for translation to other languages of the lessons in the future.

**Comment by abought** [comment]
> to avoid problems for translation to other languages of the lessons in the future.

That's a big selling point. It looks like the build process currently accepts a CSS class OR the english-language title (see `blockquote2div.py` -`SPECIAL_TITLES` and `SPECIAL_CLASSES`). But it's a bit strange for foreign language lessons to require different markup than english lessons.

**Comment by gvwilson** [comment]
I've been trying to avoid redundancy (e.g., if the title has to be 'Learning Objectives', and it has to be at the start of the topic, people shouldn't have to add `{.objectives}`).  We need the class for challenges and callouts because their titles and positions aren't known in advance; we also want to _insist_ that certain things (like learning objectives) have exactly that title in English.  So perhaps provide a language flag to the validator to tell it:
1.  what language code to look for in the YAML headers of pages, and
2.  what terms to look for in the headers of blockquotes?

**Comment by rgaiacs** [comment]
> I've been trying to avoid redundancy (e.g., if the title has to be 'Learning
> Objectives', and it has to be at the start of the topic, people shouldn't have
> to add `{.objectives}`).

I understand that but I still think that make the class attribute explicitly is
better than avoid redundancy in this case.

> So perhaps provide a language flag to the validator

I want to avoid add `language` as one of YAML header fields.

We also need to remember that this isn't only about the validator but also about
our Pandoc filter since the `blockquote` will be converted into a `div` element.
Using

```
> Learning Objectives {.objectives}
```

implies that when translate to Portuguese the translator has only to replace the
text with

```
> Objetivos da Lição {.objectives}
```

On the other hand, using

```
> Learning Objectives
```

implies that when translate to Portuguese the translator has to replace the text
with

```
> Objetivos da Lição
```

and change `tools/filters/blockquote2div.py` to properly convert the
`blockquote` element into a `div`.

**Comment by gvwilson** [comment]
OK, you've persuaded me - can you please add the attribute to Learning 
Objectives in the template, then do a sweep through all the repos and 
add it there as well?  And document the reason in lesson-template?
Thanks,
Greg

**Comment by rgaiacs** [comment]
> can you please add the attribute to Learning
> Objectives in the template, then do a sweep through all the repos and
> add it there as well?  And document the reason in lesson-template?

Sure.

**Comment by rgaiacs** [comment]
I'm closing this due #122 and #123.
